In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
data=pd.DataFrame({'id':['id1','id1','id1','id2','id2','id3'], 'f1':['a','a','a','b','b','b'],'f2':['d','d','d','c','c','d']})
data

id f1 f2
0  id1  a  d
1  id1  a  d
2  id1  a  d
3  id2  b  c
4  id2  b  c
5  id3  b  d

In [6]:
pd.crosstab(data.f1, data.f2)

f2  c  d
f1      
a   0  3
b   2  1

In [7]:
pd.crosstab(data.id, data.f1)

f1   a  b
id       
id1  3  0
id2  0  2
id3  0  1

In [9]:
pd.crosstab(data.id, [data.f1, data.f2], rownames=['id_num'], colnames=['col1', 'col2'])

col1    a  b   
col2    d  c  d
id_num         
id1     3  0  0
id2     0  2  0
id3     0  0  1

In [10]:
pd.crosstab(data.id, [data.f1, data.f2], normalize=True)

f1     a         b          
f2     d         c         d
id                          
id1  0.5  0.000000  0.000000
id2  0.0  0.333333  0.000000
id3  0.0  0.000000  0.166667

In [16]:
seri=pd.Series([0,1,2,3,4], index=['a','b','c','d','e'])
seri

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [15]:
seri[seri>=seri.mean()]

2    2
3    3
4    4
dtype: int64

In [21]:
seri.loc[['b', 'd']]

b    1
d    3
dtype: int64

In [24]:
'c' in seri.index

True

In [25]:
df=pd.DataFrame({'c1':[0,1,2,3], 'c2':[4,5,6,7], 'c3':[8,9,10,np.nan]}, index=['r1','r2','r3','r4'])
df

c1  c2    c3
r1   0   4   8.0
r2   1   5   9.0
r3   2   6  10.0
r4   3   7   NaN

In [28]:
pd.DataFrame(df, index=['r1','r3'], columns=['c1','c3'])

c1    c3
r1   0   8.0
r3   2  10.0

In [29]:
df

c1  c2    c3
r1   0   4   8.0
r2   1   5   9.0
r3   2   6  10.0
r4   3   7   NaN

In [30]:
df['c4']=df['c1']*df['c2']
df

c1  c2    c3  c4
r1   0   4   8.0   0
r2   1   5   9.0   5
r3   2   6  10.0  12
r4   3   7   NaN  21

In [31]:
df=df.assign(c5=df['c1']*df['c2'])
df

c1  c2    c3  c4  c5
r1   0   4   8.0   0   0
r2   1   5   9.0   5   5
r3   2   6  10.0  12  12
r4   3   7   NaN  21  21

In [32]:
df.assign(c6=lambda x:x.c1*x.c2)

c1  c2    c3  c4  c5  c6
r1   0   4   8.0   0   0   0
r2   1   5   9.0   5   5   5
r3   2   6  10.0  12  12  12
r4   3   7   NaN  21  21  21

In [33]:
df.drop(['c4','c5'],1)

c1  c2    c3
r1   0   4   8.0
r2   1   5   9.0
r3   2   6  10.0
r4   3   7   NaN

In [34]:
df

c1  c2    c3  c4  c5
r1   0   4   8.0   0   0
r2   1   5   9.0   5   5
r3   2   6  10.0  12  12
r4   3   7   NaN  21  21

In [35]:
del df['c4']
df

c1  c2    c3  c5
r1   0   4   8.0   0
r2   1   5   9.0   5
r3   2   6  10.0  12
r4   3   7   NaN  21

In [39]:
df['c2'][df['c2']>=5]

r2    5
r3    6
r4    7
Name: c2, dtype: int64

In [40]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [41]:
b=np.array([1,2,3,4])
c=np.array([[1,2],[3,4]])

In [43]:
np.prod(c, axis=0)
np.prod(c, axis=1)

array([ 2, 12])

In [45]:
np.sum(b)
np.sum(b, keepdims=True)

array([10])

In [47]:
np.sum(c, axis=0)
np.sum(c, axis=1)

array([3, 7])

In [48]:
d=np.array([[1,2], [3,np.nan]])
d

array([[ 1.,  2.],
       [ 3., nan]])

In [49]:
np.prod(d, axis=0)

array([ 3., nan])

In [50]:
np.nanprod(d, axis=0)

array([3., 2.])

In [51]:
f=np.arange(6).reshape(2,3)
np.cumsum(f)

array([ 0,  1,  3,  6, 10, 15], dtype=int32)

In [52]:
np.cumsum(f, axis=0)

array([[0, 1, 2],
       [3, 5, 7]], dtype=int32)

In [53]:
g=np.array([1,2,4,10,13,20])

In [54]:
np.diff(g)

array([1, 2, 6, 3, 7])

In [55]:
np.diff(g,2)

array([ 1,  4, -3,  4])

In [58]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
np.ravel(x, order='f')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [60]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [61]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [62]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [63]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [65]:
np.r_[[a,b]]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])