In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [55]:
data=pd.read_csv("tmdb_5000_movies.csv")
data=data[['id','genres','vote_average','vote_count','popularity', 'title','keywords','overview']]

In [3]:
tmp_m=data['vote_count'].quantile(0.89)
data['vote_count']>=tmp_m
tmp_data=data.copy()[data['vote_count']>=tmp_m]
tmp_data.shape

m=data['vote_count'].quantile(0.9)
data=data[data['vote_count']>=m]
data.shape

(481, 20)

In [4]:
c=data['vote_average'].mean()
c
m

1838.4000000000015

In [56]:
def weighted_rating(x, m=m, c=c):
    v=x['vote_count']
    R=x['vote_average']
    return (v/(v+m)*R)+(m/(m+v)*c)
data['score']=data.apply(weighted_rating, axis=1)

In [6]:
import ast

In [7]:
data['genres']=data['genres'].apply(ast.literal_eval)
data['keywords']=data['keywords'].apply(ast.literal_eval)

In [8]:
data['genres']=data['genres'].apply(lambda x: [d['name'] for d in x]).apply(lambda x: " ".join(x))
data['keywords']=data['keywords'].apply(lambda x: [d['name'] for d in x]).apply(lambda x: " ".join(x))

In [9]:
data.head()
data.to_csv("pre_tmdb_5000_movies.csv", index=False)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
counter_vector=CountVectorizer(ngram_range=(1,3))
c_vector_genres=counter_vector.fit_transform(data['genres'])

In [14]:
print(c_vector_genres.toarray())
print(c_vector_genres.shape)

[[1 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(481, 364)


In [15]:
counter_vector=CountVectorizer(ngram_range=(1,3))
counter_vector.fit(data['genres'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 3), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [16]:
c_vector_genres.toarray().shape
print(data.iloc[0].genres)
print(c_vector_genres.toarray()[0])
print(data.iloc[1].genres)
print(c_vector_genres.toarray()[1])

Action Adventure Fantasy Science Fiction
[1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Adventure Fantasy Action
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
c_vector_genres

<481x364 sparse matrix of type '<class 'numpy.int64'>'
	with 3238 stored elements in Compressed Sparse Row format>

In [20]:
cosine_similarity(c_vector_genres, c_vector_genres).shape
cosine_similarity(c_vector_genres, c_vector_genres)

array([[1.        , 0.47140452, 0.35355339, ..., 0.        , 0.        ,
        0.        ],
       [0.47140452, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.35355339, 0.33333333, 1.        , ..., 0.        , 0.23570226,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.23570226, ..., 0.        , 1.        ,
        0.57735027],
       [0.        , 0.        , 0.        , ..., 0.        , 0.57735027,
        1.        ]])

In [41]:
cosine_similarity(c_vector_genres, c_vector_genres)[0]
genres_c_sim=cosine_similarity(c_vector_genres, c_vector_genres).argsort()[:,::-1] # 각 영화별 코사인 유사도 값을 기준으로 내림차순 정렬

In [57]:
def get_recommend_movie_list(df, movie_title, top=30):
    target_movie_index=df[df['title']==movie_title].index.values
    sim_index=genres_c_sim[target_movie_index, :top].reshape(-1)
    sim_index=sim_index[sim_index!=target_movie_index]
    res=df.iloc[sim_index].sort_values('score', ascending=False)[:10]
    return res

get_recommend_movie_list(data, movie_title="The Dark Knight Rises")

id                                             genres  vote_average  \
316    3131  [{"id": 18, "name": "Drama"}, {"id": 36, "name...           7.1   
97   315011  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.5   
83    79698  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           4.8   
395    1581  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...           6.7   
479   77951  [{"id": 16, "name": "Animation"}, {"id": 10751...           5.2   
293   16523  [{"id": 10751, "name": "Family"}, {"id": 14, "...           6.4   
190   17578  [{"id": 12, "name": "Adventure"}, {"id": 16, "...           6.7   
312   22972  [{"id": 10752, "name": "War"}, {"id": 28, "nam...           6.4   
311   11692  [{"id": 28, "name": "Action"}, {"id": 35, "nam...           4.4   
111    1858  [{"id": 12, "name": "Adventure"}, {"id": 878, ...           6.6   

     vote_count  popularity                         title  \
316        1910   46.160048             Gangs of New York   
97          143    9.476999                 Shin Godzilla   
83           34    2.418535                    The Lovers   
395        1225   44.967453                   The Holiday   
479         133   10.088006        Walking With Dinosaurs   
293         572   31.586215     Where the Wild Things Are   
190        2061   89.938296      The Adventures of Tintin   
312         717   30.254021                    Green Zone   
311         142   12.092241  The Adventures of Pluto Nash   
111        4040   25.468493                  Transformers   

                                              keywords  \
316  [{"id": 657, "name": "fire"}, {"id": 1857, "na...   
97   [{"id": 1299, "name": "monster"}, {"id": 7671,...   
83                                                  []   
395  [{"id": 65, "name": "holiday"}, {"id": 212, "n...   
479  [{"id": 12616, "name": "dinosaur"}, {"id": 209...   
293  [{"id": 170173, "name": "children's book"}, {"...   
190  [{"id": 483, "name": "riddle"}, {"id": 1316, "...   
312  [{"id": 41177, "name": "weapon of mass destruc...   
311  [{"id": 305, "name": "moon"}, {"id": 585, "nam...   
111  [{"id": 2535, "name": "destroy"}, {"id": 4375,...   

                                              overview     score  
316  It's 1863. America was born in the streets. Am...  7.032805  
97   From the mind behind Evangelion comes a hit la...  6.929579  
83   The Lovers is an epic romance time travel adve...  6.923717  
395  Two women, one (Cameron Diaz) from America and...  6.857827  
479  Walking with Dinosaurs 3D is a film depicting ...  6.844054  
293  Max imagines running away from his mom and sai...  6.829393  
190  Intrepid young reporter, Tintin and his loyal ...  6.823990  
312  During the U.S.-led occupation of Baghdad in 2...  6.805028  
311  The year is 2087, the setting is the moon. Plu...  6.779220  
111  Young teenager, Sam Witwicky becomes involved ...  6.713522

In [27]:
x=np.array([20,10,30,13])
x.argsort()
np.sort(x)[::-1]
np.argsort(x)
np.argsort(-x)
x[np.argsort(x)]
x[np.argsort(-x)]

array([30, 20, 13, 10])

In [33]:
data=np.random.randn(4,3)
print(data)
print(data[:,0])
print(data[:,0].argsort())
print(data[:,0].argsort()[::-1])
print(data[data[:,0].argsort()[::-1]])

[[ 0.54511259  0.52543154 -1.04362138]
 [-0.701304    1.05404155 -2.01651487]
 [ 0.55062265 -1.35779168 -0.47050728]
 [ 0.74033337 -0.34245914 -0.38411407]]
[ 0.54511259 -0.701304    0.55062265  0.74033337]
[1 0 2 3]
[3 2 0 1]
[[ 0.74033337 -0.34245914 -0.38411407]
 [ 0.55062265 -1.35779168 -0.47050728]
 [ 0.54511259  0.52543154 -1.04362138]
 [-0.701304    1.05404155 -2.01651487]]


In [63]:
data=pd.read_csv("ratings_small.csv")
data=data.pivot_table('rating', index='userId', columns='movieId')
print(data)

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN     4.0     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
667         NaN     NaN     NaN     NaN     NaN     4.0     NaN     NaN   
668         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
669         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
670         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
671         5.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10     

In [67]:
movies=pd.read_csv("tmdb_5000_movies.csv")
movies.rename(columns={'id':'movieId'}, inplace=True)
movies

budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage  movieId  \
0                           http://www.avatarmovie.com/    19995   
1          http://disney.go.com/disneypictures/pirates/      285   
2           http://www.sonypictures.com/movies/spectre/   206647   
3                    http://www.thedarkknightrises.com/    49026   
4                  http://movies.disney.com/john-carter    49529   
...                                                 ...      ...   
4798                                                NaN     9367   
4799                                                NaN    72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...   231617   
4801                        http://shanghaicalling.com/   126186   
4802                                                NaN    25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   
4799                                                 []                en   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4801                                                 []                en   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he fi

In [68]:
ratings=pd.read_csv("ratings_small.csv")
ratings.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [69]:
movies.columns

Index(['budget', 'genres', 'homepage', 'movieId', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count'],
      dtype='object')

In [73]:
ratings_movies=pd.merge(ratings, movies, on="movieId")
ratings_movies[ratings_movies['userId']==2]
ratings_movies.shape

(18571, 23)

In [76]:
data=ratings_movies.pivot_table('rating', index='userId', columns='title').fillna(0)
data

(670, 856)

In [77]:
data=data.transpose()
data

userId                      1    2    3    4    5    6    7    8    9    10   \
title                                                                          
10 Things I Hate About You  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men                0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1408                        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15 Minutes                  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
16 Blocks                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
You, Me and Dupree          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Young Frankenstein          0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0   
Zodiac                      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
eXistenZ                    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx                         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                      ...  662  663  664  665  666  667  668  669  670  \
title                       ...                                                
10 Things I Hate About You  ...  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men                ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1408                        ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15 Minutes                  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
16 Blocks                   ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
You, Me and Dupree          ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Young Frankenstein          ...  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0   
Zodiac                      ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
eXistenZ                    ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx                         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                      671  
title                            
10 Things I Hate About You  0.0  
12 Angry Men                0.0  
1408                        0.0  
15 Minutes                  0.0  
16 Blocks                   0.0  
...                         ...  
You, Me and Dupree          0.0  
Young Frankenstein          0.0  
Zodiac                      0.0  
eXistenZ                    0.0  
xXx                         0.0  

[856 rows x 670 columns]

In [80]:
movie_sim=cosine_similarity(data, data)

In [84]:
data.index

Index(['10 Things I Hate About You', '12 Angry Men', '1408', '15 Minutes',
       '16 Blocks', '20,000 Leagues Under the Sea', '2001: A Space Odyssey',
       '2046', '21 Grams', '25th Hour',
       ...
       'Willy Wonka & the Chocolate Factory', 'World Trade Center',
       'X-Men Origins: Wolverine', 'Y Tu Mamá También', 'You Only Live Twice',
       'You, Me and Dupree', 'Young Frankenstein', 'Zodiac', 'eXistenZ',
       'xXx'],
      dtype='object', name='title', length=856)

In [87]:
type(movie_sim)
movie_sim_df=pd.DataFrame(movie_sim, index=data.index, columns=data.index)
movie_sim_df

title                       10 Things I Hate About You  12 Angry Men  \
title                                                                  
10 Things I Hate About You                    1.000000           0.0   
12 Angry Men                                  0.000000           1.0   
1408                                          0.000000           0.0   
15 Minutes                                    0.182153           0.0   
16 Blocks                                     0.000000           0.0   
...                                                ...           ...   
You, Me and Dupree                            0.000000           0.0   
Young Frankenstein                            0.097588           0.0   
Zodiac                                        0.000000           0.0   
eXistenZ                                      0.000000           0.0   
xXx                                           0.014121           0.0   

title                           1408  15 Minutes  16 Blocks  \
title                                                         
10 Things I Hate About You  0.000000    0.182153        0.0   
12 Angry Men                0.000000    0.000000        0.0   
1408                        1.000000    0.447214        0.0   
15 Minutes                  0.447214    1.000000        0.0   
16 Blocks                   0.000000    0.000000        1.0   
...                              ...         ...        ...   
You, Me and Dupree          0.000000    0.000000        0.0   
Young Frankenstein          0.191675    0.085720        0.0   
Zodiac                      0.000000    0.115684        0.0   
eXistenZ                    0.000000    0.121365        0.0   
xXx                         0.000000    0.000000        0.0   

title                       20,000 Leagues Under the Sea  \
title                                                      
10 Things I Hate About You                      0.022069   
12 Angry Men                                    0.000000   
1408                                            0.173381   
15 Minutes                                      0.077538   
16 Blocks                                       0.000000   
...                                                  ...   
You, Me and Dupree                              0.000000   
Young Frankenstein                              0.204590   
Zodiac                                          0.014016   
eXistenZ                                        0.000000   
xXx                                             0.092985   

title                       2001: A Space Odyssey  2046  21 Grams  25th Hour  \
title                                                                          
10 Things I Hate About You               0.085323   0.0   0.00000   0.103490   
12 Angry Men                             0.000000   0.0   0.00000   0.000000   
1408                                     0.028245   0.0   0.00000   0.000000   
15 Minutes                               0.050526   0.0   0.00000   0.129863   
16 Blocks                                0.000000   0.0   0.00000   0.000000   
...                                           ...   ...       ...        ...   
You, Me and Dupree                       0.000000   0.0   0.00000   0.000000   
Young Frankenstein                       0.115720   0.0   0.00000   0.000000   
Zodiac                                   0.222842   0.0   0.00000   0.075115   
eXistenZ                                 0.079525   0.0   0.07253   0.000000   
xXx                                      0.069771   0.0   0.00000   0.000000   

title                       ...  Willy Wonka & the Chocolate Factory  \
title                       ...                                        
10 Things I Hate About You  ...                             0.059856   
12 Angry Men                ...                             0.000000   
1408                        ...                             0.146955   
15 Minutes                  ...                             0

In [91]:
movie_sim_df['X-Men Origins: Wolverine'].sort_values(ascending=False)[1:11]

title
Romeo Must Die                        0.649625
The Wedding Planner                   0.631669
Dogtown and Z-Boys                    0.501189
An Unfinished Life                    0.485643
Conquest of the Planet of the Apes    0.474626
Reign Over Me                         0.458155
The Terminal                          0.445337
Young Frankenstein                    0.423840
Whale Rider                           0.394136
Madagascar                            0.392497
Name: X-Men Origins: Wolverine, dtype: float64

In [ ]:
rating.csv와 movies.csv 두 파일을 읽어서 추천시스템 제작
1. 아이텐 기반 추천
2. 사용자 기반 추천
