In [ ]:
# MultiCampus200810.ipynb 에 오전 수업 내용

In [1]:
import numpy as np

In [3]:
myArr=np.arange(1000000)

In [5]:
myList=list(range(10000000))

In [8]:
%time for _ in range(30):    myArr=myArr*2

Wall time: 67 ms


In [12]:
myList2=[]
%time for _ in range(30): myList2=[x*2 for x in myList]
#for i in range(len(myList)):
#    myList2.append(myList[i]*2)
#myList2

Wall time: 23.1 s


In [15]:
data=np.random.randn(2, 3)

In [16]:
data*10

array([[ 14.72019231, -12.10349079,  -8.71274423],
       [  6.45796875, -10.72532803,   1.97759511]])

In [18]:
data.shape
data.dtype

dtype('float64')

In [20]:
data1=[3, 1.4, 2, 0]
arr1=np.array(data1)

In [25]:
data2=[[1, 2, 3], [4, 5, 6]]
arr2=np.array(data2)
arr2.ndim
arr2.shape
arr2.dtype

dtype('int32')

In [28]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
ones=np.ones((2,3,4,5))
ones.shape

(2, 3, 4, 5)

In [36]:
arr=np.array([1, 2, 3], dtype=np.float64)
arr

array([1., 2., 3.])

In [38]:
arr=np.array(['1.5', '-2.7'])
arr.astype(float)

array([ 1.5, -2.7])

In [42]:
arr=np.array(([1, 2, 3], [4, 5, 6]))

In [43]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [44]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [45]:
arr2=np.array([[0,1,2],[7,8,9]])

In [46]:
arr>arr2

array([[ True,  True,  True],
       [False, False, False]])

In [47]:
arr=np.arange(10)

In [48]:
arrslice=arr[5:8]

In [49]:
arrslice[:]=777
arrslice

array([777, 777, 777])

In [50]:
arr

array([  0,   1,   2,   3,   4, 777, 777, 777,   8,   9])

In [51]:
arrslice2=arr[5:8].copy()

In [53]:
arrslice2[0]=333

In [55]:
arrslice2

array([333, 777, 777])

In [56]:
arr

array([  0,   1,   2,   3,   4, 777, 777, 777,   8,   9])

In [59]:
arr2=np.array([[1,2], [3,4], [5,6]])
arr2[2][1]

6

In [62]:
arr=np.array(list(range(1, 25)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [64]:
arr3d=arr.reshape(2, 3, 4)
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [65]:
oldValues=arr3d[0].copy()

In [69]:
arr3d[0]=oldValues

In [66]:
arr3d[0]=999

In [70]:
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [71]:
arr3d[1][2]

array([21, 22, 23, 24])