In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [38]:
data=pd.read_csv("tmdb_5000_movies.csv")
data.shape
data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [39]:
data=data[['id','genres','vote_average','vote_count','popularity', 'title','keywords','overview']]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
id              4803 non-null int64
genres          4803 non-null object
vote_average    4803 non-null float64
vote_count      4803 non-null int64
popularity      4803 non-null float64
title           4803 non-null object
keywords        4803 non-null object
overview        4800 non-null object
dtypes: float64(2), int64(2), object(4)
memory usage: 300.3+ KB


In [40]:
tmp_m=data['vote_count'].quantile(0.89)
data['vote_count']>=tmp_m
tmp_data=data.copy()[data['vote_count']>=tmp_m]
tmp_data.shape

m=data['vote_count'].quantile(0.9)
data=data[data['vote_count']>=m]
data.shape

(481, 8)

In [41]:
c=data['vote_average'].mean()
c
m

1838.4000000000015

In [42]:
def weighted_rating(x, m=m, c=c):
    v=x['vote_count']
    R=x['vote_average']
    return (v/(v+m)*R)+(m/(m+v)*c)
data['score']=data.apply(weighted_rating, axis=1)

In [43]:
data.head()

id                                             genres  vote_average  \
0   19995  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     285  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  206647  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3   49026  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4   49529  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                     title  \
0       11800  150.437577                                    Avatar   
1        4500  139.082615  Pirates of the Caribbean: At World's End   
2        4466  107.376788                                   Spectre   
3        9106  112.312950                     The Dark Knight Rises   
4        2124   43.926995                               John Carter   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview     score  
0  In the 22nd century, a paraplegic Marine is di...  7.168053  
1  Captain Barbossa, long believed to be dead, ha...  6.918271  
2  A cryptic message from Bond’s past sends him o...  6.493333  
3  Following the death of District Attorney Harve...  7.492998  
4  John Carter is a war-weary, former military ca...  6.500396

In [44]:
data[['genres', 'keywords']].head()

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4  [{"id": 818, "name": "based on novel"}, {"id":...

In [46]:
import ast
listStr='[1, 2, 3, 4, 5]'
ast.literal_eval(listStr)

[1, 2, 3, 4, 5]

In [48]:
data['genres']=data['genres'].apply(ast.literal_eval)

In [49]:
data['keywords']=data['keywords'].apply(ast.literal_eval)

In [50]:
data[['genres','keywords']]

genres  \
0     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
3     [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...   
4     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
...                                                 ...   
4291  [{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...   
4300  [{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...   
4302                    [{'id': 37, 'name': 'Western'}]   
4337  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...   
4602                      [{'id': 18, 'name': 'Drama'}]   

                                               keywords  
0     [{'id': 1463, 'name': 'culture clash'}, {'id':...  
1     [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...  
2     [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...  
3     [{'id': 849, 'name': 'dc comics'}, {'id': 853,...  
4     [{'id': 818, 'name': 'based on novel'}, {'id':...  
...                                                 ...  
4291  [{'id': 1366, 'name': 'shotgun'}, {'id': 13000...  
4300  [{'id': 2052, 'name': 'traitor'}, {'id': 6099,...  
4302  [{'id': 801, 'name': 'bounty hunter'}, {'id': ...  
4337  [{'id': 422, 'name': 'vietnam veteran'}, {'id'...  
4602  [{'id': 934, 'name': 'judge'}, {'id': 1417, 'n...  

[481 rows x 2 columns]

In [60]:
data.iloc[0]['genres']
data.iloc[1]['keywords']

[{'id': 270, 'name': 'ocean'},
 {'id': 726, 'name': 'drug abuse'},
 {'id': 911, 'name': 'exotic island'},
 {'id': 1319, 'name': 'east india trading company'},
 {'id': 2038, 'name': "love of one's life"},
 {'id': 2052, 'name': 'traitor'},
 {'id': 2580, 'name': 'shipwreck'},
 {'id': 2660, 'name': 'strong woman'},
 {'id': 3799, 'name': 'ship'},
 {'id': 5740, 'name': 'alliance'},
 {'id': 5941, 'name': 'calypso'},
 {'id': 6155, 'name': 'afterlife'},
 {'id': 6211, 'name': 'fighter'},
 {'id': 12988, 'name': 'pirate'},
 {'id': 157186, 'name': 'swashbuckler'},
 {'id': 179430, 'name': 'aftercreditsstinger'}]

In [64]:
eval("(5*2)/4")
eval("max([1,2,3])")
s2="{'a':3,'b':5}"
ast.literal_eval(s2)['b']

5

In [70]:
data['genres']=data['genres'].apply(lambda x: [d['name'] for d in x]).apply(lambda x: " ".join(x))

In [69]:
data['keywords']=data['keywords'].apply(lambda x: [d['name'] for d in x]).apply(lambda x: " ".join(x))

In [72]:
data.head()
data.to_csv("pre_tmdb_5000_movies.csv", index=False)

In [75]:
##### 컨텐츠(성별, 장르, 토픽, 예산 ...) 기반 필터링 -> 추천 시스템
# 장르 (문자열) -> 숫자로 변환 -> 벡터화 작업
from sklearn.feature_extraction import *

In [73]:
data.genres

0       Action Adventure Fantasy Science Fiction
1                       Adventure Fantasy Action
2                         Action Adventure Crime
3                    Action Crime Drama Thriller
4               Action Adventure Science Fiction
                          ...                   
4291                        Horror Mystery Crime
4300                              Crime Thriller
4302                                     Western
4337                                 Crime Drama
4602                                       Drama
Name: genres, Length: 481, dtype: object

In [81]:
v=DictVectorizer(sparse=False)
D=[{'A':1, 'B':2}, {'B':3, 'C':1}]
x=v.fit_transform(D)
x # bow 출력
v.feature_names_
v.transform({'C':4, 'D':2})

array([[0., 0., 4.]])

In [95]:
#CountVectorizer
corpus=['This is the first documnet',
       'This is the second second documnet',
       'And the third one',
       'The last documnet']
cv=CountVectorizer()
cv.fit(corpus)
print(cv.vocabulary_)
print(cv.transform(corpus).toarray())

{'this': 9, 'is': 3, 'the': 7, 'first': 2, 'documnet': 1, 'second': 6, 'and': 0, 'third': 8, 'one': 5, 'last': 4}
[[0 1 1 1 0 0 0 1 0 1]
 [0 1 0 1 0 0 2 1 0 1]
 [1 0 0 0 0 1 0 1 1 0]
 [0 1 0 0 1 0 0 1 0 0]]


In [87]:
cv.transform(['Something completely new']).toarray()
cv.transform(['This is the third doc']).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [90]:
cv=CountVectorizer(stop_words=['is','the'])
cv.fit(corpus)
print(cv.vocabulary_)
print(cv.transform(corpus).toarray())

{'this': 7, 'first': 2, 'documnet': 1, 'second': 5, 'and': 0, 'thirs': 6, 'one': 4, 'last': 3}
[[0 1 1 0 0 0 0 1]
 [0 1 0 0 0 2 0 1]
 [1 0 0 0 1 0 1 0]
 [0 1 0 1 0 0 0 0]]


In [96]:
cv=CountVectorizer(stop_words='english')
cv.fit(corpus)
print(cv.vocabulary_)

{'documnet': 0, 'second': 1}


In [98]:
cv.get_stop_words()

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides'

In [99]:
cv=CountVectorizer(analyzer='char')
cv.fit(corpus)
cv.vocabulary_

{'t': 14,
 'h': 6,
 'i': 7,
 's': 13,
 ' ': 0,
 'e': 4,
 'f': 5,
 'r': 12,
 'd': 3,
 'o': 11,
 'c': 2,
 'u': 15,
 'm': 9,
 'n': 10,
 'a': 1,
 'l': 8}

In [109]:
cv=CountVectorizer(token_pattern="th\w+")
cv.fit(corpus)
cv.vocabulary_

{'this': 2, 'the': 0, 'third': 1}

In [106]:
cv=CountVectorizer(ngram_range=(2,2))
cv.fit(corpus)
cv.vocabulary_

{'this is': 11,
 'is the': 2,
 'the first': 6,
 'first documnet': 1,
 'the second': 8,
 'second second': 5,
 'second documnet': 4,
 'and the': 0,
 'the third': 9,
 'third one': 10,
 'the last': 7,
 'last documnet': 3}

In [108]:
cv=CountVectorizer(ngram_range=(1,2), token_pattern="t\w+")
cv.fit(corpus)
cv.vocabulary_

{'this': 3, 'the': 0, 'this the': 4, 'third': 2, 'the third': 1}

In [114]:
cv=CountVectorizer(min_df=2)
cv.fit(corpus)
cv.vocabulary_

{'this': 3, 'is': 1, 'the': 2, 'documnet': 0}

In [116]:
cv.transform(corpus).toarray()
cv.transform(corpus).toarray().sum(axis=0)

array([3, 2, 4, 2], dtype=int64)

In [117]:
# 1. fit_transform 함수를 이용한 장르 벡터화
counter_vector=CountVectorizer(ngram_range=(1,3))
c_vector_genres=counter_vector.fit_transform(data['genres'])

In [118]:
print(c_vector_genres.toarray())
print(c_vector_genres.shape)

[[1 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(481, 364)


In [120]:
# 2. fit & transform 함수를 이용한 장르 벡터화
counter_vector=CountVectorizer(ngram_range=(1,3))
counter_vector.fit(data['genres'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 3), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [122]:
len(counter_vector.get_feature_names())

364

In [125]:
data.iloc[0]

id                                                          19995
genres                   Action Adventure Fantasy Science Fiction
vote_average                                                  7.2
vote_count                                                  11800
popularity                                                150.438
title                                                      Avatar
keywords        culture clash future space war space colony so...
overview        In the 22nd century, a paraplegic Marine is di...
score                                                     7.16805
Name: 0, dtype: object

In [128]:
c_vector_genres.toarray().shape
print(data.iloc[0].genres)
print(c_vector_genres.toarray()[0])
print(data.iloc[1].genres)
print(c_vector_genres.toarray()[1])

Action Adventure Fantasy Science Fiction
[1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Adventure Fantasy Action
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 