In [1]:
import numpy as np
import pandas as pd

In [5]:
df1=pd.DataFrame({'c1':np.arange(5), 'c2':np.random.randn(5)}, index=['r0','r1','r2','r3','r4'])
df1
df1=df1.reindex(['r0','r1','r2','r5','r6'], fill_value=0)
df1

c1        c2
r0   0 -0.835634
r1   1  0.945404
r2   2 -0.254970
r5   0  0.000000
r6   0  0.000000

In [7]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2'],
    'D':['D0','D1','D2']
})

In [8]:
df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5'],
    'D':['D3','D4','D5']
}, index=[3,4,5])

In [10]:
pd.concat([df1, df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [11]:
df3 = pd.DataFrame({'E': ['A6', 'A7', 'A8'],
    'F': ['B6', 'B7', 'B8'],
    'G': ['C6', 'C7', 'C8'],
    'H': ['D6', 'D7', 'D8']},
    index=[0, 1, 2])

In [12]:
print(df1)
print(df3)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
    E   F   G   H
0  A6  B6  C6  D6
1  A7  B7  C7  D7
2  A8  B8  C8  D8


In [14]:
pd.concat([df1, df3], axis=1)

A   B   C   D   E   F   G   H
0  A0  B0  C0  D0  A6  B6  C6  D6
1  A1  B1  C1  D1  A7  B7  C7  D7
2  A2  B2  C2  D2  A8  B8  C8  D8

In [15]:
df4 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'E': ['E0', 'E1', 'E2']},
     index=[0, 1, 3])

In [16]:
print(df1)
print(df4)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
    A   B   C   E
0  A0  B0  C0  E0
1  A1  B1  C1  E1
3  A2  B2  C2  E2


In [22]:
print(pd.concat([df1, df4], join='outer'))
print(pd.concat([df1, df4], join='inner'))
print(pd.concat([df1, df4], join='outer', axis=1))
print(pd.concat([df1, df4], join='inner', axis=1))

    A   B   C    D    E
0  A0  B0  C0   D0  NaN
1  A1  B1  C1   D1  NaN
2  A2  B2  C2   D2  NaN
0  A0  B0  C0  NaN   E0
1  A1  B1  C1  NaN   E1
3  A2  B2  C2  NaN   E2
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A0  B0  C0
1  A1  B1  C1
3  A2  B2  C2
     A    B    C    D    A    B    C    E
0   A0   B0   C0   D0   A0   B0   C0   E0
1   A1   B1   C1   D1   A1   B1   C1   E1
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN   A2   B2   C2   E2
    A   B   C   D   A   B   C   E
0  A0  B0  C0  D0  A0  B0  C0  E0
1  A1  B1  C1  D1  A1  B1  C1  E1


C:\Users\msi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [26]:
df5 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'D': ['D0', 'D1', 'D2']},
     index=['r0', 'r1', 'r2'])


df6 = pd.DataFrame({'A': ['A3', 'A4', 'A5'],
     'B': ['B3', 'B4', 'B5'],
     'C': ['C3', 'C4', 'C5'],
     'D': ['D3', 'D4', 'D5']},
     index=['r3', 'r4', 'r5'])

In [31]:
print(df5)
print(df6)
pd.concat([df5,df6])

     A   B   C   D
r0  A0  B0  C0  D0
r1  A1  B1  C1  D1
r2  A2  B2  C2  D2
     A   B   C   D
r3  A3  B3  C3  D3
r4  A4  B4  C4  D4
r5  A5  B5  C5  D5


A   B   C   D
r0  A0  B0  C0  D0
r1  A1  B1  C1  D1
r2  A2  B2  C2  D2
r3  A3  B3  C3  D3
r4  A4  B4  C4  D4
r5  A5  B5  C5  D5

In [32]:
pd.concat([df5,df6], ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [38]:
df56_with_keys=pd.concat([df5,df6], keys=['d5','d6'], names=['dfName', 'rowNum'])
df56_with_keys

A   B   C   D
dfName rowNum                
d5     r0      A0  B0  C0  D0
       r1      A1  B1  C1  D1
       r2      A2  B2  C2  D2
d6     r3      A3  B3  C3  D3
       r4      A4  B4  C4  D4
       r5      A5  B5  C5  D5

In [37]:
df56_with_keys.loc['d5'].loc['r1']

A    A1
B    B1
C    C1
D    D1
Name: r1, dtype: object

In [39]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']},
    index=[0, 1, 2])

In [46]:
s1=pd.Series(['S1','S2', 'S3'], name='S')

In [47]:
pd.concat([df1, s1])

A    B    C    D    0
0   A0   B0   C0   D0  NaN
1   A1   B1   C1   D1  NaN
2   A2   B2   C2   D2  NaN
0  NaN  NaN  NaN  NaN   S1
1  NaN  NaN  NaN  NaN   S2
2  NaN  NaN  NaN  NaN   S3

In [48]:
pd.concat([df1, s1], axis=1)

A   B   C   D   S
0  A0  B0  C0  D0  S1
1  A1  B1  C1  D1  S2
2  A2  B2  C2  D2  S3

In [49]:
pd.concat([df1, s1], axis=1, ignore_index=True)

0   1   2   3   4
0  A0  B0  C0  D0  S1
1  A1  B1  C1  D1  S2
2  A2  B2  C2  D2  S3

In [50]:
s1=pd.Series(['S1','S2', 'S3'], name='S')
s2=pd.Series([0,1, 2])
s3=pd.Series([3,4,5])

In [54]:
print(type(pd.concat([s1,s2],axis=1)))
pd.concat([s1,s2],axis=1)

<class 'pandas.core.frame.DataFrame'>


S  0
0  S1  0
1  S2  1
2  S3  2

In [56]:
pd.concat([s1,s2,s3],axis=1,keys=['c0','c1','c2'])

c0  c1  c2
0  S1   0   3
1  S2   1   4
2  S3   2   5

In [57]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [60]:
s4=pd.Series(['S1', 'S2', 'S3', 'S4'], index=['A','B','C','E'])
s4

A    S1
B    S2
C    S3
E    S4
dtype: object

In [61]:
df1.append(s4, ignore_index=True)

A   B   C    D    E
0  A0  B0  C0   D0  NaN
1  A1  B1  C1   D1  NaN
2  A2  B2  C2   D2  NaN
3  S1  S2  S3  NaN   S4

In [63]:
arr=np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
arr+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [65]:
arr+arr

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [67]:
np.concatenate([arr, arr])
np.concatenate([arr, arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [68]:
s1=pd.Series([0,1], index=['a','b'])
s2=pd.Series([2,3,4], index=['c','d','e'])
s3=pd.Series([5,6], index=['f','g'])
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [70]:
s4=pd.concat([s1*5,s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [71]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  5

In [72]:
#s1,s1,s3 세개의 시리즈 합침(위아래로)
pd.concat([s1,s1,s3]) #계층인덱스:one,two,three
res=pd.concat([s1,s1,s3],keys=['one','two','three'])
res

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [73]:
res.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [74]:
res=pd.concat([s1,s1,s3],keys=['one','two','three'],axis=1) #default:axis=0
res

C:\Users\msi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


one  two  three
a  0.0  0.0    NaN
b  1.0  1.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [76]:
df1=pd.DataFrame(np.arange(6).reshape(3,2), index=['a','b','c'], columns=['one','two'])
df1

one  two
a    0    1
b    2    3
c    4    5

In [77]:
df2=pd.DataFrame(np.arange(4).reshape(2,2)+5, index=['a','c'], columns=['three','four'])
df2

three  four
a      5     6
c      7     8

In [79]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

C:\Users\msi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [83]:
pd.concat({'level1':df1, 'level2':df2}, axis=1, names=['L1','L2'])

C:\Users\msi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


L1 level1     level2     
L2    one two  three four
a       0   1    5.0  6.0
b       2   3    NaN  NaN
c       4   5    7.0  8.0

In [85]:
a=pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan], index=['f','e','d','c','b','a'])
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [86]:
b=pd.Series(np.arange(len(a), dtype=np.float64), index=['f','e','d','c','b','a'])
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [103]:
pd.concat([a, b], axis=1)
np.array(np.where(pd.isnull(a), 0, a)+b)
np.array(a.fillna(0)+b)

array([0. , 3.5, 2. , 6.5, 8.5, 5. ])

In [107]:
dfleft = pd.DataFrame({'KEY': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']})
dfleft

KEY   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [114]:
dfright = pd.DataFrame({'KEY': ['K2', 'K3', 'K4', 'K5'],
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']})
dfright

KEY   C   D
0  K2  C2  D2
1  K3  C3  D3
2  K4  C4  D4
3  K5  C5  D5

In [115]:
pd.merge(dfleft, dfright)

KEY   A   B   C   D
0  K2  A2  B2  C2  D2
1  K3  A3  B3  C3  D3

In [116]:
pd.merge(dfleft, dfright, how='outer')

KEY    A    B    C    D
0  K0   A0   B0  NaN  NaN
1  K1   A1   B1  NaN  NaN
2  K2   A2   B2   C2   D2
3  K3   A3   B3   C3   D3
4  K4  NaN  NaN   C4   D4
5  K5  NaN  NaN   C5   D5

In [117]:
pd.merge(dfleft, dfright, how='right')

KEY    A    B   C   D
0  K2   A2   B2  C2  D2
1  K3   A3   B3  C3  D3
2  K4  NaN  NaN  C4  D4
3  K5  NaN  NaN  C5  D5

In [119]:
pd.merge(dfleft, dfright, on="KEY", how="outer", indicator=True)

KEY    A    B    C    D      _merge
0  K0   A0   B0  NaN  NaN   left_only
1  K1   A1   B1  NaN  NaN   left_only
2  K2   A2   B2   C2   D2        both
3  K3   A3   B3   C3   D3        both
4  K4  NaN  NaN   C4   D4  right_only
5  K5  NaN  NaN   C5   D5  right_only

In [122]:
dfright = pd.DataFrame({'A': ['A0', 'A1', 'A2','A3'],
    'B': ['B0', 'B1', 'B2','B3']},index=['K0','K1','K2','K3'])
dfleft=pd.DataFrame({'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']},
    index=['K2', 'K3', 'K4', 'K5'])
print(dfleft)
print(dfright)

     C   D
K2  C0  D0
K3  C1  D1
K4  C2  D2
K5  C3  D3
     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
K3  A3  B3


In [125]:
pd.merge(dfright, dfleft, right_index=True, left_index=True, how='left')

A   B    C    D
K0  A0  B0  NaN  NaN
K1  A1  B1  NaN  NaN
K2  A2  B2   C0   D0
K3  A3  B3   C1   D1

In [126]:
pd.merge(dfright, dfleft, right_index=True, left_index=True, how='right')

A    B   C   D
K2   A2   B2  C0  D0
K3   A3   B3  C1  D1
K4  NaN  NaN  C2  D2
K5  NaN  NaN  C3  D3

In [127]:
dfleft.join(dfright, how='right')

C    D   A   B
K0  NaN  NaN  A0  B0
K1  NaN  NaN  A1  B1
K2   C0   D0  A2  B2
K3   C1   D1  A3  B3

In [128]:
dfleft.join(dfright, how='outer')

C    D    A    B
K0  NaN  NaN   A0   B0
K1  NaN  NaN   A1   B1
K2   C0   D0   A2   B2
K3   C1   D1   A3   B3
K4   C2   D2  NaN  NaN
K5   C3   D3  NaN  NaN

In [129]:
dfleft=pd.DataFrame({'KEY':['K0','K1','K2','K3'], 
                    'A':['A0','A1','A2','A3'],
                    'B':[0.5,2.1,3.1,0.3]})
dfleft

KEY   A    B
0  K0  A0  0.5
1  K1  A1  2.1
2  K2  A2  3.1
3  K3  A3  0.3

In [130]:
dfright=pd.DataFrame({'KEY':['K2','K3','K4','K5'], 
                    'C':['C0','C1','C2','C3'],
                    'D':['D2','D3','D4','D5']})
dfright

KEY   C   D
0  K2  C0  D2
1  K3  C1  D3
2  K4  C2  D4
3  K5  C3  D5

In [157]:
dfall=pd.merge(dfleft, dfright, how='outer')
dfall

KEY    A    B    C    D
0  K0   A0  0.5  NaN  NaN
1  K1   A1  2.1  NaN  NaN
2  K2   A2  3.1   C0   D2
3  K3   A3  0.3   C1   D3
4  K4  NaN  NaN   C2   D4
5  K5  NaN  NaN   C3   D5

In [134]:
pd.isnull(dfall)

KEY      A      B      C      D
0  False  False  False   True   True
1  False  False  False   True   True
2  False  False  False  False  False
3  False  False  False  False  False
4  False   True   True  False  False
5  False   True   True  False  False

In [135]:
pd.notnull(dfall)

KEY      A      B      C      D
0  True   True   True  False  False
1  True   True   True  False  False
2  True   True   True   True   True
3  True   True   True   True   True
4  True  False  False   True   True
5  True  False  False   True   True

In [158]:
dfall

KEY    A    B    C    D
0  K0   A0  0.5  NaN  NaN
1  K1   A1  2.1  NaN  NaN
2  K2   A2  3.1   C0   D2
3  K3   A3  0.3   C1   D3
4  K4  NaN  NaN   C2   D4
5  K5  NaN  NaN   C3   D5

In [166]:
dfall.loc[[0,1],['A','B']]=None
dfall
dfall[['A','B']].isnull()

A      B
0   True   True
1   True   True
2  False  False
3  False  False
4   True   True
5   True   True

In [167]:
dfall.isnull().sum()

KEY    0
A      4
B      4
C      2
D      2
dtype: int64

In [169]:
dfall['NanCnt']=dfall.isnull().sum(axis=1)
dfall

KEY     A    B    C    D  NanCnt
0  K0  None  NaN  NaN  NaN       4
1  K1  None  NaN  NaN  NaN       4
2  K2    A2  3.1   C0   D2       0
3  K3    A3  0.3   C1   D3       0
4  K4   NaN  NaN   C2   D4       2
5  K5   NaN  NaN   C3   D5       2