In [1]:
from keras import models
from keras import layers
from keras import optimizers, losses, metrics
from keras import preprocessing

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import re

from konlpy.tag import Okt

In [2]:
chatbot_data=pd.read_csv("ChatbotData .csv")

In [3]:
question, answer=list(chatbot_data['Q']), list(chatbot_data['A'])

In [4]:
question = question[:100]
answer = answer[:100]

In [5]:
for i in range(10):
    print('Q : ' + question[i])
    print('A : ' + answer[i])
    print()

Q : 12시 땡!
A : 하루가 또 가네요.

Q : 1지망 학교 떨어졌어
A : 위로해 드립니다.

Q : 3박4일 놀러가고 싶다
A : 여행은 언제나 좋죠.

Q : 3박4일 정도 놀러가고 싶다
A : 여행은 언제나 좋죠.

Q : PPL 심하네
A : 눈살이 찌푸려지죠.

Q : SD카드 망가졌어
A : 다시 새로 사는 게 마음 편해요.

Q : SD카드 안돼
A : 다시 새로 사는 게 마음 편해요.

Q : SNS 맞팔 왜 안하지ㅠㅠ
A : 잘 모르고 있을 수도 있어요.

Q : SNS 시간낭비인 거 아는데 매일 하는 중
A : 시간을 정하고 해보세요.

Q : SNS 시간낭비인데 자꾸 보게됨
A : 시간을 정하고 해보세요.



In [6]:
# 정규 표현식 필터
RE_FILTER = re.compile("[.,!?\"':;~()]")

In [7]:
def pos_tag(sentences):
# KoNLPy 형태소분석기 설정
    tagger = Okt()
    # 문장 품사 변수 초기화
    sentences_pos = []
    for sentence in sentences:
        # 특수기호 제거
        sentence = re.sub(RE_FILTER, "", sentence)
        #print(tagger.morphs(sentence))
        sentence = " ".join(tagger.morphs(sentence))
        sentences_pos.append(sentence)
    return sentences_pos

In [8]:
# 형태소분석 수행
question = pos_tag(question)
answer = pos_tag(answer)

In [9]:
for i in range(10):
    print('Q : ' + question[i])
    print('A : ' + answer[i])
    print()

Q : 12시 땡
A : 하루 가 또 가네요

Q : 1 지망 학교 떨어졌어
A : 위로 해 드립니다

Q : 3 박 4일 놀러 가고 싶다
A : 여행 은 언제나 좋죠

Q : 3 박 4일 정도 놀러 가고 싶다
A : 여행 은 언제나 좋죠

Q : PPL 심하네
A : 눈살 이 찌푸려지죠

Q : SD 카드 망가졌어
A : 다시 새로 사는 게 마음 편해요

Q : SD 카드 안 돼
A : 다시 새로 사는 게 마음 편해요

Q : SNS 맞팔 왜 안 하지 ㅠㅠ
A : 잘 모르고 있을 수도 있어요

Q : SNS 시간 낭비 인 거 아는데 매일 하는 중
A : 시간 을 정 하고 해보세요

Q : SNS 시간 낭비 인데 자꾸 보게 됨
A : 시간 을 정 하고 해보세요



In [10]:
sentences=[]
sentences.extend(question)

In [11]:
sentences.extend(answer)
sentences

['12시 땡',
 '1 지망 학교 떨어졌어',
 '3 박 4일 놀러 가고 싶다',
 '3 박 4일 정도 놀러 가고 싶다',
 'PPL 심하네',
 'SD 카드 망가졌어',
 'SD 카드 안 돼',
 'SNS 맞팔 왜 안 하지 ㅠㅠ',
 'SNS 시간 낭비 인 거 아는데 매일 하는 중',
 'SNS 시간 낭비 인데 자꾸 보게 됨',
 'SNS 보면 나 만 빼고 다 행복 해보여',
 '가끔 궁금해',
 '가끔 뭐 하는지 궁금해',
 '가끔 은 혼자 인게 좋다',
 '가난한 자의 설움',
 '가만 있어도 땀 난다',
 '가상 화폐 쫄딱 망함',
 '가스 불 켜고 나갔어',
 '가스 불 켜놓고 나온거 같아',
 '가스 비 너무 많이 나왔다',
 '가스 비 비싼데 감기 걸리겠어',
 '가스 비 장난 아님',
 '가장 확실한 건 뭘 까',
 '가족 여행 가기 로 했어',
 '가족 여행 고고',
 '가족 여행 어디 로 가지',
 '가족 있어',
 '가족 관계 알려 줘',
 '가족 끼리 여행 간다',
 '가족 들 보고 싶어',
 '가족 들 이랑 서먹해',
 '가족 들 이랑 서먹해졌어',
 '가족 들 이랑 어디 가지',
 '가족 들 이랑 여행 갈거야',
 '가족 여행 가야 지',
 '가족 이 누구 야',
 '가족 이랑 여행 가려고',
 '가족 한테 스트레스 풀었어',
 '가출 할까',
 '가출 해도 갈 데 가 없어',
 '간만 에 떨리니까 좋더라',
 '간만 에 쇼핑 중',
 '간만 에 휴식 중',
 '간식 뭐 먹을까',
 '간식 추천',
 '간장 치킨 시켜야지',
 '간접흡연 싫어',
 '갈까 말까 고민 돼',
 '갈까 말까',
 '감 말랭이 먹고 싶다',
 '감 말랭이 먹어야지',
 '감기 같 애',
 '감기 걸린 것 같아',
 '감기 기운 이 있어',
 '감기 들 거 같 애',
 '감기 가 오려나',
 '감기 약 이 없어',
 '감기 인거 같 애',
 '감미로운 목소리 좋아',
 '감정 이 쓰레기통 처럼 엉망 진창 이야',
 '감정 컨트롤 을 못 하겠어',
 '감정 컨

In [12]:
words = []

In [13]:
for sentence in sentences:
    for word in sentence.split():
        words.append(word)


In [14]:
words

['12시',
 '땡',
 '1',
 '지망',
 '학교',
 '떨어졌어',
 '3',
 '박',
 '4일',
 '놀러',
 '가고',
 '싶다',
 '3',
 '박',
 '4일',
 '정도',
 '놀러',
 '가고',
 '싶다',
 'PPL',
 '심하네',
 'SD',
 '카드',
 '망가졌어',
 'SD',
 '카드',
 '안',
 '돼',
 'SNS',
 '맞팔',
 '왜',
 '안',
 '하지',
 'ㅠㅠ',
 'SNS',
 '시간',
 '낭비',
 '인',
 '거',
 '아는데',
 '매일',
 '하는',
 '중',
 'SNS',
 '시간',
 '낭비',
 '인데',
 '자꾸',
 '보게',
 '됨',
 'SNS',
 '보면',
 '나',
 '만',
 '빼고',
 '다',
 '행복',
 '해보여',
 '가끔',
 '궁금해',
 '가끔',
 '뭐',
 '하는지',
 '궁금해',
 '가끔',
 '은',
 '혼자',
 '인게',
 '좋다',
 '가난한',
 '자의',
 '설움',
 '가만',
 '있어도',
 '땀',
 '난다',
 '가상',
 '화폐',
 '쫄딱',
 '망함',
 '가스',
 '불',
 '켜고',
 '나갔어',
 '가스',
 '불',
 '켜놓고',
 '나온거',
 '같아',
 '가스',
 '비',
 '너무',
 '많이',
 '나왔다',
 '가스',
 '비',
 '비싼데',
 '감기',
 '걸리겠어',
 '가스',
 '비',
 '장난',
 '아님',
 '가장',
 '확실한',
 '건',
 '뭘',
 '까',
 '가족',
 '여행',
 '가기',
 '로',
 '했어',
 '가족',
 '여행',
 '고고',
 '가족',
 '여행',
 '어디',
 '로',
 '가지',
 '가족',
 '있어',
 '가족',
 '관계',
 '알려',
 '줘',
 '가족',
 '끼리',
 '여행',
 '간다',
 '가족',
 '들',
 '보고',
 '싶어',
 '가족',
 '들',
 '이랑',
 '서먹해',
 '가족',
 '들',
 '이랑',
 '서먹해졌어',
 '가

In [15]:
words = [word for word in words if len(word) > 0]
words = list(set(words))

In [16]:
PAD = "<PADDING>"   # 패딩
STA = "<START>"     # 시작
END = "<END>"       # 끝
OOV = "<OOV>"       # 없는 단어(Out of Vocabulary)

In [17]:
# 제일 앞에 태그 단어 삽입
words[:0] = [PAD, STA, END, OOV]
words

['<PADDING>',
 '<START>',
 '<END>',
 '<OOV>',
 '보내고',
 '누구',
 '걸린',
 '나',
 '이다',
 '잊고',
 '망함',
 '됐으면',
 '쉬는',
 '요',
 '갑자기',
 '드세요',
 '오늘이',
 '곧',
 '운',
 '때',
 '또',
 '습관',
 '나갔어',
 '싶은데',
 '살쪄도',
 '이에요',
 '입어볼까',
 '일해',
 '룩',
 '이나',
 '좋다',
 '진창',
 '갈까',
 '놓고',
 '어필',
 '가상',
 '있어',
 '부터는',
 '집어서',
 '12시',
 '감',
 '기회',
 '힘든데',
 '하루',
 '돼',
 '말까',
 '감미로운',
 '고고',
 '절약',
 '게임',
 '개인',
 '화폐',
 '편해요',
 '키우고',
 '제일',
 '그',
 '가네요',
 '맞팔',
 '가장',
 '보고',
 '들어올',
 '했길',
 '인거',
 '보고싶었나',
 '무시',
 '당황',
 '좋아해주세요',
 '떨어졌어',
 '봐서',
 '어서',
 '좋더라',
 '할까',
 '서먹해졌어',
 '잘',
 '진리',
 '싫어하지',
 '바라요',
 '피',
 '까지',
 '어제',
 '적',
 '드는',
 '내',
 '식혀주세요',
 '옆',
 '가고',
 '예쁘게',
 '곳',
 '하지',
 '했잖아',
 '다',
 '너무',
 '기관',
 '오려나',
 '은',
 '정말',
 '로',
 '서로',
 '장난',
 '중요한',
 '연락',
 '붙잡고',
 '만',
 '있으면',
 '중요해요',
 '아님',
 '소중해요',
 '휴식',
 '확실한',
 '약',
 '가야',
 '땡',
 '위로',
 '수영장',
 '까',
 '들',
 '했어',
 'SNS',
 '중',
 '감히',
 '들더라',
 '하세요',
 '취미',
 '싫다',
 '먼저',
 '돌아가서',
 '싶다',
 '드립니다',
 '좋겠네요',
 '죠',
 '보면',
 '생각',
 '놀러',
 '뭐',
 '간접흡연',
 

In [18]:
# 단어와 인덱스의 딕셔너리 생성
word_to_index = {word: index for index, word in enumerate(words)}
index_to_word = {index: word for index, word in enumerate(words)}

In [19]:
# 한 문장에서 단어 시퀀스의 최대 개수
max_sequences = 30

In [20]:
# 데이터 타입
ENCODER_INPUT  = 0
DECODER_INPUT  = 1
DECODER_TARGET = 2

In [21]:
# 문장을 인덱스로 변환
def convert_text_to_index(sentences, vocabulary, type): 
    sentences_index = [] #문장 -> 단어 -> 인덱스 -> 저장

    # 모든 문장에 대해서 반복
    for sentence in sentences: #sentence = "12시 땡"
        sentence_index = [] #각각의 문장을 구성하는 단어들에 대한 index가 저장되는 리스트 변수

        # 디코더 입력일 경우 맨 앞에 START 태그 추가
        if type == DECODER_INPUT:
            sentence_index.extend([vocabulary[STA]])

        # 문장의 단어들을 띄어쓰기로 분리
        for word in sentence.split(): #[12시,땡]
            if vocabulary.get(word) is not None:
                # 사전에 있는 단어면 해당 인덱스를 추가
                sentence_index.extend([vocabulary[word]])                
            else: # 사전에 없는 단어면 OOV 인덱스를 추가
                sentence_index.extend([vocabulary[OOV]])
# 최대 길이 검사
        if type == DECODER_TARGET:
            # 디코더 목표일 경우 맨 뒤에 END 태그 추가
            if len(sentence_index) >= max_sequences:
                sentence_index = sentence_index[:max_sequences-1] + [vocabulary[END]]
            else:
                sentence_index += [vocabulary[END]]
        else:
            if len(sentence_index) > max_sequences:
                sentence_index = sentence_index[:max_sequences]
            
        # 최대 길이에 없는 공간은 패딩 인덱스로 채움
        sentence_index += (max_sequences - len(sentence_index)) * [vocabulary[PAD]]

        
        sentences_index.append(sentence_index)

    return np.array(sentences_index)

In [22]:
x_encoder = convert_text_to_index(question, word_to_index, ENCODER_INPUT)
# 첫 번째 인코더 입력 출력 (12시 땡)
x_encoder[0]

array([ 39, 111,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0])

In [23]:
# 디코더 입력 인덱스 변환
x_decoder = convert_text_to_index(answer, word_to_index, DECODER_INPUT)

# 첫 번째 디코더 입력 출력 (START 하루 가 또 가네요)
x_decoder[0]

array([  1,  43, 260,  20,  56,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0])

In [24]:
# 디코더 목표 인덱스 변환
y_decoder = convert_text_to_index(answer, word_to_index, DECODER_TARGET)

# 첫 번째 디코더 목표 출력 (하루 가 또 가네요 END)
y_decoder[0]

array([ 43, 260,  20,  56,   2,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0])

In [25]:
# 원핫인코딩 초기화
one_hot_data = np.zeros((len(y_decoder), max_sequences, len(words)))

# 디코더 목표를 원핫인코딩으로 변환
# 학습시 입력은 인덱스이지만, 출력은 원핫인코딩 형식임
for i, sequence in enumerate(y_decoder):
    for j, index in enumerate(sequence):
        one_hot_data[i, j, index] = 1

# 디코더 목표 설정
y_decoder = one_hot_data

# 첫 번째 디코더 목표 출력
y_decoder[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [26]:
# 임베딩 벡터 차원
embedding_dim = 100
# LSTM 히든레이어 차원
lstm_hidden_dim = 128

In [27]:
# 입력 문장의 인덱스 시퀀스를 입력으로 받음
encoder_inputs = layers.Input(shape=(None,))

# 임베딩 레이어
encoder_outputs = layers.Embedding(len(words), embedding_dim)(encoder_inputs)

# return_state가 True면 상태값 리턴
# LSTM은 state_h(hidden state)와 state_c(cell state) 2개의 상태 존재
encoder_outputs, state_h, state_c = layers.LSTM(lstm_hidden_dim,
                                                dropout=0.1,
                                                recurrent_dropout=0.5,
                                                return_state=True)(encoder_outputs)

# 히든 상태와 셀 상태를 하나로 묶음
encoder_states = [state_h, state_c]

In [28]:
# 목표 문장의 인덱스 시퀀스를 입력으로 받음
decoder_inputs = layers.Input(shape=(None,))

# 임베딩 레이어
decoder_embedding = layers.Embedding(len(words), embedding_dim)
decoder_outputs = decoder_embedding(decoder_inputs)

# 인코더와 달리 return_sequences를 True로 설정하여 모든 타임 스텝 출력값 리턴
# 모든 타임 스텝의 출력값들을 다음 레이어의 Dense()로 처리하기 위함
decoder_lstm = layers.LSTM(lstm_hidden_dim,
                           dropout=0.1,
                           recurrent_dropout=0.5,
                           return_state=True,
                           return_sequences=True)

# initial_state를 인코더의 상태로 초기화
decoder_outputs, _, _ = decoder_lstm(decoder_outputs,
                                     initial_state=encoder_states)

# 단어의 개수만큼 노드의 개수를 설정하여 원핫 형식으로 각 단어 인덱스를 출력
decoder_dense = layers.Dense(len(words), activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

In [29]:
#--------------------------------------------
# 훈련 모델 정의
#--------------------------------------------

# 입력과 출력으로 함수형 API 모델 생성
model = models.Model([encoder_inputs, decoder_inputs], decoder_outputs)

# 학습 방법 설정
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [30]:
# 훈련 모델의 인코더 상태를 사용하여 예측 모델 인코더 설정
encoder_model = models.Model(encoder_inputs, encoder_states)

In [31]:
#--------------------------------------------
# 예측 모델 디코더 정의
#--------------------------------------------

# 예측시에는 훈련시와 달리 타임 스텝을 한 단계씩 수행
# 매번 이전 디코더 상태를 입력으로 받아서 새로 설정
decoder_state_input_h = layers.Input(shape=(lstm_hidden_dim,))
decoder_state_input_c = layers.Input(shape=(lstm_hidden_dim,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]    

# 임베딩 레이어
decoder_outputs = decoder_embedding(decoder_inputs)

# LSTM 레이어
decoder_outputs, state_h, state_c = decoder_lstm(decoder_outputs,
                                                 initial_state=decoder_states_inputs)

# 히든 상태와 셀 상태를 하나로 묶음
decoder_states = [state_h, state_c]

# Dense 레이어를 통해 원핫 형식으로 각 단어 인덱스를 출력
decoder_outputs = decoder_dense(decoder_outputs)

# 예측 모델 디코더 설정
decoder_model = models.Model([decoder_inputs] + decoder_states_inputs,
                      [decoder_outputs] + decoder_states)

In [32]:
# 인덱스를 문장으로 변환
def convert_index_to_text(indexs, vocabulary): 
    
    sentence = ''
    
    # 모든 문장에 대해서 반복
    for index in indexs:
        if index == END_INDEX:
            # 종료 인덱스면 중지
            break;
        if vocabulary.get(index) is not None:
            # 사전에 있는 인덱스면 해당 단어를 추가
            sentence += vocabulary[index]
        else:
            # 사전에 없는 인덱스면 OOV 단어를 추가
            sentence.extend([vocabulary[OOV_INDEX]])
            
        # 빈칸 추가
        sentence += ' '

    return sentence

In [34]:
# 태그 인덱스
PAD_INDEX = 0
STA_INDEX = 1
END_INDEX = 2
OOV_INDEX = 3

In [35]:
# 에폭 반복
for epoch in range(20):
    print('Total Epoch :', epoch + 1)

    # 훈련 시작
    history = model.fit([x_encoder, x_decoder],
                        y_decoder,
                        epochs=100,
                        batch_size=64,
                        verbose=0)
    
    # 정확도와 손실 출력
    print('accuracy :', history.history['accuracy'][-1])
    print('loss :', history.history['loss'][-1])
    
    # 문장 예측 테스트
    # (3 박 4일 놀러 가고 싶다) -> (여행 은 언제나 좋죠)
    input_encoder = x_encoder[2].reshape(1, x_encoder[2].shape[0])
    input_decoder = x_decoder[2].reshape(1, x_decoder[2].shape[0])
    results = model.predict([input_encoder, input_decoder])
    
    # 결과의 원핫인코딩 형식을 인덱스로 변환
    # 1축을 기준으로 가장 높은 값의 위치를 구함
    indexs = np.argmax(results[0], 1) 
    
    # 인덱스를 문장으로 변환
    sentence = convert_index_to_text(indexs, index_to_word)
    print(sentence)
    print()

Total Epoch : 1
accuracy : 0.9243333339691162
loss : 0.3649039566516876
저 도 언제나 좋죠 

Total Epoch : 2
accuracy : 0.9666666388511658
loss : 0.15130791068077087
여행 은 언제나 좋죠 

Total Epoch : 3
accuracy : 0.9743333458900452
loss : 0.08835263550281525
가세 은 언제나 좋죠 

Total Epoch : 4
accuracy : 0.9776666760444641
loss : 0.06722718477249146
여행 은 언제나 좋죠 

Total Epoch : 5
accuracy : 0.984333336353302
loss : 0.04842160642147064
여행 은 언제나 좋죠 

Total Epoch : 6
accuracy : 0.9896666407585144
loss : 0.031004130840301514
여행 은 언제나 좋죠 

Total Epoch : 7
accuracy : 0.9956666827201843
loss : 0.01638961397111416
여행 은 언제나 좋죠 

Total Epoch : 8
accuracy : 0.9983333349227905
loss : 0.008174587041139603
여행 은 언제나 좋죠 

Total Epoch : 9
accuracy : 0.999666690826416
loss : 0.003811128670349717
여행 은 언제나 좋죠 

Total Epoch : 10
accuracy : 0.999666690826416
loss : 0.0022974975872784853
여행 은 언제나 좋죠 

Total Epoch : 11
accuracy : 0.9986666440963745
loss : 0.004056469537317753
여행 은 언제나 좋죠 

Total Epoch : 12
accuracy : 0.9990000128

In [39]:
# 예측을 위한 입력 생성
def make_predict_input(sentence):

    sentences = []
    sentences.append(sentence)
    sentences = pos_tag(sentences)
    input_seq = convert_text_to_index(sentences, word_to_index, ENCODER_INPUT)
    
    return input_seq
# 텍스트 생성
def generate_text(input_seq):
    
    # 입력을 인코더에 넣어 마지막 상태 구함
    states = encoder_model.predict(input_seq)

    # 목표 시퀀스 초기화
    target_seq = np.zeros((1, 1))
    
    # 목표 시퀀스의 첫 번째에 <START> 태그 추가
    target_seq[0, 0] = STA_INDEX
    
    # 인덱스 초기화
    indexs = []
    while 1:
        # 디코더로 현재 타임 스텝 출력 구함
        # 처음에는 인코더 상태를, 다음부터 이전 디코더 상태로 초기화
        decoder_outputs, state_h, state_c = decoder_model.predict(
                                                [target_seq] + states)

        # 결과의 원핫인코딩 형식을 인덱스로 변환
        index = np.argmax(decoder_outputs[0, 0, :])
        indexs.append(index)
        
        # 종료 검사
        if index == END_INDEX or len(indexs) >= max_sequences:
            break

        # 목표 시퀀스를 바로 이전의 출력으로 설정
        target_seq = np.zeros((1, 1))
        target_seq[0, 0] = index
        
        # 디코더의 이전 상태를 다음 디코더 예측에 사용
        states = [state_h, state_c]

        # 인덱스를 문장으로 변환
        sentence = convert_index_to_text(indexs, index_to_word)
        
    return sentence

In [40]:
# 문장을 인덱스로 변환
input_seq = make_predict_input('3박4일 놀러가고 싶다')
input_seq
# 예측 모델로 텍스트 생성
sentence = generate_text(input_seq)
sentence
# 문장을 인덱스로 변환
input_seq = make_predict_input('3박4일 같이 놀러가고 싶다')
input_seq
# 문장을 인덱스로 변환
input_seq = make_predict_input('3박4일 놀러가려고')
input_seq
# 예측 모델로 텍스트 생성
sentence = generate_text(input_seq)
sentence

'여행 은 언제나 좋죠 '