In [1]:
import numpy as np

In [2]:
#np.where 함수 == x if 조건 else y
xarr=np.array([1, 2, 3, 4, 5])
yarr=np.array([2, 3, 4, 5, 6])
cond=np.array([True, False, True, True, False])
#True일 때는 xarr, False일 때는 yarr
res=[(x if c else y)for x, y, c in zip(xarr, yarr, cond)]
res
#파이썬 수행 -> 큰 배열이라면 매우 속도가 늦음

[1, 3, 3, 4, 6]

In [4]:
res2=np.where(cond, xarr, yarr)#매우 빠르고 간결하게 수행
res2

array([1, 3, 3, 4, 6])

In [6]:
arr=np.random.randn(4, 4)
#arr에 저장된 값이 양수이면 값을 2로, 음수이면 0 으로 변경

np.where(arr>0, 2, 0)

array([[0, 0, 0, 2],
       [0, 2, 2, 2],
       [0, 2, 2, 2],
       [0, 0, 2, 0]])

In [8]:
np.where(arr>0, 2, arr)

array([[-0.56100116, -0.58879476, -1.34093054,  2.        ],
       [-1.70128894,  2.        ,  2.        ,  2.        ],
       [-0.39394096,  2.        ,  2.        ,  2.        ],
       [-0.11243448, -0.09381069,  2.        , -0.45556987]])

In [10]:
#수학, 통계 메서드
arr=np.random.randn(5, 4)

In [11]:
arr.mean()

0.1912441346468753

In [12]:
np.mean(arr)

0.1912441346468753

In [13]:
np.sum(arr)

3.824882692937506

In [14]:
arr.mean(axis=1)

array([-0.03976408,  0.02952569,  0.59391516,  0.18119774,  0.19134616])

In [15]:
arr.mean(axis=0)

array([0.08332863, 0.1208034 , 0.42140843, 0.13943607])

In [17]:
arr=np.arange(8)

In [18]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [22]:
arr=np.arange(9).reshape(3, 3)
print(arr.cumsum())
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[ 0  1  3  6 10 15 21 28 36]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


In [23]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [25]:
#Boolean 배열 메서드
arr=np.random.randn(100)
arr

array([ 0.40599373,  0.88135386,  0.04741069,  0.94729943,  1.57063827,
       -0.35075016, -1.35695469, -0.17041026, -1.34248464, -1.36125129,
        2.91133292, -1.52222385, -0.87366013,  1.07837535,  1.61922472,
        0.18074759,  0.95138481, -1.33868072,  1.0019693 , -0.17793414,
       -0.90918161, -1.17301046,  0.9551997 , -0.31908214,  0.30823545,
        1.19732258, -0.32230455, -1.24054983,  0.23313126, -1.78635293,
        0.01768154, -1.92256373,  0.22940815,  0.88480311,  0.50245788,
       -0.01166671,  0.36170389,  0.13211925, -0.16827982,  0.27369967,
       -0.1879503 ,  0.34060191, -0.62374061, -0.65789687,  0.58786171,
       -0.45608363, -0.10450402, -1.5141861 , -0.90241168, -0.26581245,
        1.21667515, -0.71400793, -0.60563695,  1.77850938, -0.68108268,
        1.69019487,  0.87230988, -0.00310685,  0.33600127,  0.6446891 ,
        0.13716123,  0.87897009, -0.34831851, -0.70046242,  0.14221118,
       -0.87112813, -0.43303075, -0.22288975, -1.15803745,  1.05

In [26]:
arr>0

array([ True,  True,  True,  True,  True, False, False, False, False,
       False,  True, False, False,  True,  True,  True,  True, False,
        True, False, False, False,  True, False,  True,  True, False,
       False,  True, False,  True, False,  True,  True,  True, False,
        True,  True, False,  True, False,  True, False, False,  True,
       False, False, False, False, False,  True, False, False,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
       False,  True, False, False, False, False,  True,  True, False,
        True,  True, False,  True, False,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True,
        True, False, False,  True, False, False, False, False, False,
       False])

In [27]:
(arr>0).sum()

45

In [29]:
bools=np.array([False, False, True, False])
print(bools.any())
print(bools.all())

True
False


In [31]:
arr=np.random.randn(6)
arr

array([ 0.90522438,  0.00697132,  0.26854462,  0.33764375, -1.1375279 ,
       -0.85258335])

In [34]:
arr.sort()
arr

array([-1.1375279 , -0.85258335,  0.00697132,  0.26854462,  0.33764375,
        0.90522438])

In [35]:
arr=np.random.randn(5,3)
arr

array([[ 0.27614659,  0.59017039,  1.9301878 ],
       [ 0.31346665,  0.45511002,  1.0959841 ],
       [ 0.10795062,  1.67260491, -3.2054932 ],
       [ 2.6646767 , -1.40762453,  2.0102164 ],
       [-1.25283727,  0.33750974,  1.85688606]])

In [36]:
arr.sort()
arr

array([[ 0.27614659,  0.59017039,  1.9301878 ],
       [ 0.31346665,  0.45511002,  1.0959841 ],
       [-3.2054932 ,  0.10795062,  1.67260491],
       [-1.40762453,  2.0102164 ,  2.6646767 ],
       [-1.25283727,  0.33750974,  1.85688606]])

In [37]:
arr.sort(0)
arr

array([[-3.2054932 ,  0.10795062,  1.0959841 ],
       [-1.40762453,  0.33750974,  1.67260491],
       [-1.25283727,  0.45511002,  1.85688606],
       [ 0.27614659,  0.59017039,  1.9301878 ],
       [ 0.31346665,  2.0102164 ,  2.6646767 ]])

In [40]:
x=np.array([3, 2, 5, 4, 1, 9, 0])

In [39]:
x.sort()
x

array([0, 1, 2, 3, 4, 5, 9])

In [41]:
np.sort(x)

array([0, 1, 2, 3, 4, 5, 9])

In [42]:
x

array([3, 2, 5, 4, 1, 9, 0])

In [43]:
np.sort(x)[::-1]

array([9, 5, 4, 3, 2, 1, 0])

In [46]:
x
np.argsort(x) # x에 저장되어있는 데이터를 오름차순 정렬 결과에 대한 원 데이터에 대한 index 출력

array([6, 4, 1, 0, 3, 2, 5], dtype=int64)

In [47]:
x=np.arange(1, 10).reshape(3,3)

In [50]:
print(np.sort(x, axis=1)) # 행 단위 오름차순
print(np.sort(x, 1)[::-1]) # 열 축 기준으로 거꾸로 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [51]:
names=np.array(['순신', '길동', '꺽정', '길동', '길동'])

In [52]:
np.unique(names)

array(['길동', '꺽정', '순신'], dtype='<U2')

In [53]:
set(names)

{'길동', '꺽정', '순신'}

In [54]:
np.in1d(names, ['순신', '길동'])

array([ True,  True, False,  True,  True])

In [55]:
# np.save(), np.load() : 1개의 배열을 바이너리로 저장
x=np.array([0, 1, 2])
np.save("xsave", x) # x에 저장된 배열을 xsave.npy로 저장

In [56]:
xload=np.load("xsave.npy")
xload

array([0, 1, 2])

In [57]:
x=np.array([1, 2, 3])
y=np.array([4, 5, 6])
np.savez("xysavez", x=x, y=y)

In [58]:
xyload=np.load("xysavez.npz")
xyload

In [59]:
xyload['x']

array([1, 2, 3])

In [60]:
xyload['y']

array([4, 5, 6])

In [62]:
xyload.close()
#xload.close()

In [65]:
# np.savetxt : 여러 개의 배열을 텍스트 파일로 저장
# np.loadtxt : 텍스트 파일을 배열로 불러오기
x=np.array([1, 2, 3])
y=np.array([4, 5, 6])
np.savetxt("xytxt.txt", (x, y), fmt="%.f")

In [66]:
xyload=np.loadtxt("xytxt.txt")
xyload

array([[1., 2., 3.],
       [4., 5., 6.]])

In [67]:
# numpy 배열을 여러개로 분할(split)
# hsplit : 수평축으로 배열 분할
# vsplit : 수직축으로 배열 분할
x=np.arange(18).reshape(3, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [73]:
np.hsplit(x, 3) # x배열을 수평축으로 3개의 배열로 분할
np.hsplit(x, (2, 4))
np.split(x, 3, axis=1)
x1, x2, x3=np.split(x, (2, 4), axis=1)
x1

array([[ 0,  1],
       [ 6,  7],
       [12, 13]])

In [74]:
x=np.arange(18).reshape(3, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [76]:
np.vsplit(x, 3)
np.vsplit(x, (1, 2))

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [77]:
arr=np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
arr[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [79]:
np.flip(arr, axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [80]:
np.flip(arr, axis=1)

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [81]:
arr[:, ::-1]

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [82]:
arr[:, ::-1][::-1]

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [83]:
np.flip(arr)

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [100]:
a=np.arange(-5, 5)
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [92]:
#1. 리스트 컴프리헨션
res=[0 if i<0 else i for i in a]
res

[0, 0, 0, 0, 0, 0, 1, 2, 3, 4]

In [96]:
#2. 불린 참조
a[a<0]=0
a

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])

In [97]:
#3. np.where
np.where(a<0, 0, a)

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])

In [98]:
np.where(a<0, 0, np.where(a>2, 2, a))

array([0, 0, 0, 0, 0, 0, 1, 2, 2, 2])

In [105]:
np.clip(a, 0, 2, out=a)
a

array([0, 0, 0, 0, 0, 0, 1, 2, 2, 2])

In [106]:
a=[1, 2, 3]
np.asarray(a)

array([1, 2, 3])

In [109]:
a=[1,2]

In [110]:
b=np.array([1, 2])
b

array([1, 2])

In [112]:
b2=np.asarray(a)
b2

array([1, 2])

In [113]:
b is b2 # 주소가 다르다

False

In [115]:
b=np.array([1, 2])
np.asarray(b) is b # 주소가 같다

True

In [116]:
# 단위행렬(항등행렬) : 정방행렬 && 대각성분 '1', 나머지는  '0'
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
np.random.choice(5,10)

array([3, 0, 0, 0, 2, 2, 2, 1, 0, 4])

In [121]:
# 비균등 확률로 표본 복원 추출
p=[0.1, 0.2, 0.2, 0.4, 0.1] # 각 원소별 표본으로 뽑힐 확률
np.random.choice(5, 3) # 0~4까지 각각의 수가 뽑힐 확률은 균등하게 0.2
np.random.choice(5, 3, p=p) # p=표본이 추출될 확률

array([3, 3, 4])

In [122]:
np.random.choice(5, 3, replace=False) # 비복원 추출

array([4, 1, 2])

In [123]:
fruits=['apple', 'banana', 'mange', 'lemon']
p=[0.05, 0.05, 0.7, 0.2]
np.random.choice(fruits, 2, p=p, replace=False)

array(['mange', 'lemon'], dtype='<U6')

In [124]:
# np.random.seed() : 
np.random.seed(1004)
np.random.choice(5, 3)

array([2, 3, 3])

In [ ]:
# 데이터 수집->전처리->분석->모델링->모델평가 및 개선
# 모델? 데이터 입력 -> 모델 -> 예측/분류 결과 출력
# ex) 전체 데이터 100개  => 모델 (X)
#     70개 데이터(훈련 데이터) => 모델링 / 30개 데이터(테스트 데이터) => 모델 평가 (O)
#     30개 중 21개 정담 -> 70% 정확도 모델

In [127]:
# train / test 데이터 분할
# 1. Scikit-Learn
x=np.arange(20).reshape(10, 2) # (중간고사 등수 , 기말고사 등수)
y=np.arange(10) # 최종시험 등수

In [128]:
from sklearn.model_selection import train_test_split

In [134]:
xTrain, xTest, yTrain, yTest=train_test_split(x, y, test_size=0.3, random_state=1004) # 훈련 : 60%, 테스트 : 40%

In [136]:
# 브로드 캐스팅
a=np.array([1,2,3])
b=np.array([1,2])
a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [137]:
np.arange(3)+5

array([5, 6, 7])

In [138]:
np.arange(11, 20).reshape(3, 3)+np.arange(3)

array([[11, 13, 15],
       [14, 16, 18],
       [17, 19, 21]])

In [140]:
np.arange(3).reshape(3, 1)+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [146]:
arr3d=np.array([[[0, 1], [2, 3], [4, 5], [6, 7]], [[8, 9], [10 ,11], [12, 13], [14, 15]], [[16, 17], [18, 19], [20, 21], [22, 23]]])

In [144]:
arr2d=np.arange(0, 8).reshape(4, 2)

In [147]:
arr3d+arr2d

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]]])