In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
billboard=pd.read_csv("billboard.csv")
billboard

year            artist                    track  time date.entered  wk1  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87   
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91   
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08   81   
3    2000      3 Doors Down                    Loser  4:24   2000-10-21   76   
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   57   
..    ...               ...                      ...   ...          ...  ...   
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   86   
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   85   
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   95   
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   99   
316  2000   matchbox twenty                     Bent  4:12   2000-04-29   60   

      wk2   wk3   wk4   wk5  ...  wk67  wk68  wk69  wk70  wk71  wk72  wk73  \
0    82.0  72.0  77.0  87.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1    87.0  92.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2    70.0  68.0  67.0  66.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3    76.0  72.0  69.0  67.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4    34.0  25.0  17.0  17.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   
312  83.0  77.0  74.0  83.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
313  83.0  83.0  82.0  81.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
314  94.0  91.0  85.0  84.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
315  99.0   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
316  37.0  29.0  24.0  22.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     wk74  wk75  wk76  
0     NaN   NaN   NaN  
1     NaN   NaN   NaN  
2     NaN   NaN   NaN  
3     NaN   NaN   NaN  
4     NaN   NaN   NaN  
..    ...   ...   ...  
312   NaN   NaN   NaN  
313   NaN   NaN   NaN  
314   NaN   NaN   NaN  
315   NaN   NaN   NaN  
316   NaN   NaN   NaN  

[317 rows x 81 columns]

In [6]:
billboard_long=pd.melt(billboard, id_vars=['year', 'artist', 'track', 'time', 'date.entered'], var_name='week', value_name='rating')
billboard_long.shape

(24092, 7)

In [7]:
billboard_long[billboard_long.track=='Loser']

year        artist  track  time date.entered  week  rating
3      2000  3 Doors Down  Loser  4:24   2000-10-21   wk1    76.0
320    2000  3 Doors Down  Loser  4:24   2000-10-21   wk2    76.0
637    2000  3 Doors Down  Loser  4:24   2000-10-21   wk3    72.0
954    2000  3 Doors Down  Loser  4:24   2000-10-21   wk4    69.0
1271   2000  3 Doors Down  Loser  4:24   2000-10-21   wk5    67.0
...     ...           ...    ...   ...          ...   ...     ...
22510  2000  3 Doors Down  Loser  4:24   2000-10-21  wk72     NaN
22827  2000  3 Doors Down  Loser  4:24   2000-10-21  wk73     NaN
23144  2000  3 Doors Down  Loser  4:24   2000-10-21  wk74     NaN
23461  2000  3 Doors Down  Loser  4:24   2000-10-21  wk75     NaN
23778  2000  3 Doors Down  Loser  4:24   2000-10-21  wk76     NaN

[76 rows x 7 columns]

In [9]:
billboard_song=billboard_long[['year','artist','track','time']]
billboard_song

year            artist                    track  time
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22
1      2000           2Ge+her  The Hardest Part Of ...  3:15
2      2000      3 Doors Down               Kryptonite  3:53
3      2000      3 Doors Down                    Loser  4:24
4      2000          504 Boyz            Wobble Wobble  3:35
...     ...               ...                      ...   ...
24087  2000       Yankee Grey     Another Nine Minutes  3:10
24088  2000  Yearwood, Trisha          Real Live Woman  3:55
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19
24090  2000     Zombie Nation            Kernkraft 400  3:30
24091  2000   matchbox twenty                     Bent  4:12

[24092 rows x 4 columns]

In [10]:
billboard_song=billboard_song.drop_duplicates()
billboard_song

year            artist                    track  time
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22
1    2000           2Ge+her  The Hardest Part Of ...  3:15
2    2000      3 Doors Down               Kryptonite  3:53
3    2000      3 Doors Down                    Loser  4:24
4    2000          504 Boyz            Wobble Wobble  3:35
..    ...               ...                      ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10
313  2000  Yearwood, Trisha          Real Live Woman  3:55
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19
315  2000     Zombie Nation            Kernkraft 400  3:30
316  2000   matchbox twenty                     Bent  4:12

[317 rows x 4 columns]

In [12]:
billboard_song['id']=range(len(billboard_song))

C:\Users\msi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [14]:
billboard_rating=billboard_long.merge(billboard_song, on=['year','artist','track','time'])
billboard_rating

year           artist                    track  time date.entered  \
0      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
1      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
2      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
3      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
4      2000            2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
...     ...              ...                      ...   ...          ...   
24087  2000  matchbox twenty                     Bent  4:12   2000-04-29   
24088  2000  matchbox twenty                     Bent  4:12   2000-04-29   
24089  2000  matchbox twenty                     Bent  4:12   2000-04-29   
24090  2000  matchbox twenty                     Bent  4:12   2000-04-29   
24091  2000  matchbox twenty                     Bent  4:12   2000-04-29   

       week  rating   id  
0       wk1    87.0    0  
1       wk2    82.0    0  
2       wk3    72.0    0  
3       wk4    77.0    0  
4       wk5    87.0    0  
...     ...     ...  ...  
24087  wk72     NaN  316  
24088  wk73     NaN  316  
24089  wk74     NaN  316  
24090  wk75     NaN  316  
24091  wk76     NaN  316  

[24092 rows x 8 columns]

In [17]:
a1=np.ones((2,3))
a2=np.zeros((3,3))
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
a1=np.ones((3,4))
a2=np.zeros((3,4))
print(np.dstack([a1,a2]).shape)
np.dstack([a1,a2])

(3, 4, 2)


array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [23]:
print(np.stack([a1,a2]).shape)
np.stack([a1,a2])
np.stack([a1,a2], axis=1)
np.stack([a1,a2], axis=2)

(2, 3, 4)


array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [24]:
np.r_[np.array([1,2,3]),np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [25]:
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
a=np.array([[1,2,3],[4,5,6]])
np.tile(a,2)
np.tile(a, (3,2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [29]:
myList=list("ABCDE")
myArr=np.round(np.random.rand(3,5),2)

In [35]:
df1=pd.DataFrame(np.vstack([myList,myArr]).T, columns=['C1','C2','C3','C4'])
df1

C1    C2    C3    C4
0  A  0.34  0.17  0.54
1  B  0.63  0.79  0.97
2  C  0.33  0.78  0.22
3  D  0.04  0.93  0.45
4  E   0.4  0.84  0.09

In [38]:
df2=df1.set_index('C1')
df2.set_index('C2')

C3    C4
C2              
0.34  0.17  0.54
0.63  0.79  0.97
0.33  0.78  0.22
0.04  0.93  0.45
0.4   0.84  0.09

In [40]:
df2.reset_index()
df2.reset_index(drop=True)

C2    C3    C4
0  0.34  0.17  0.54
1  0.63  0.79  0.97
2  0.33  0.78  0.22
3  0.04  0.93  0.45
4   0.4  0.84  0.09

In [41]:
pd.DataFrame(np.random.randn(5,4))

0         1         2         3
0 -1.676537 -2.570299  0.053501  0.781653
1  0.480202 -1.354067  0.313690  1.364287
2  0.166179  0.950646  0.471573  0.395065
3 -0.584392  0.500195 -1.156961  0.719237
4  0.047093 -0.812271  0.853048 -0.158952

In [44]:
mi=pd.MultiIndex.from_tuples([('A','C1'),('A','C2'),('B','C3'),('B','C4')])
pd.DataFrame(np.random.randn(5,4), columns=mi)
df3=pd.DataFrame(np.random.randn(5,4), columns=[['A','A','B','B'],['C1','C2','C3','C4']])

In [45]:
df3.columns.names=['Cidx1','Cidx2']
df3

Cidx1         A                   B          
Cidx2        C1        C2        C3        C4
0     -1.565349 -0.942739  1.024874  0.422878
1     -0.118554 -0.578489 -2.152546  1.437231
2      1.186515 -1.364812  0.244146 -0.850399
3      0.701248  1.961744 -1.010617 -0.126414
4     -0.602868  0.405450 -1.349425 -0.116044

In [48]:
df4=pd.DataFrame(np.random.randn(6,4), columns=[['A','A', 'B','B'],['C','C','D','D']], index=[['M','M','M','F','F','F'], ["id"+str(i+1) for i in range(3)]*2])
df4.columns.names=['cidx1','cidx2']
df4.index.names=['ridx1','ridx2']
df4

cidx1               A                   B          
cidx2               C         C         D         D
ridx1 ridx2                                        
M     id1    0.848911  1.801001  0.075272  0.534270
      id2   -1.326139 -0.425197  0.175670 -1.307304
      id3   -1.084448  1.029029 -0.594710 -0.222529
F     id1   -0.027381 -2.450827  0.262664  1.436538
      id2    1.029116  1.111909 -0.347283  0.219508
      id3    1.541434  0.912654  0.356962  0.351822

In [50]:
df4.stack("cidx1")
df4.stack("cidx2")

cidx1                     A         B
ridx1 ridx2 cidx2                    
M     id1   C      0.848911  0.075272
            D      1.801001  0.534270
      id2   C     -1.326139  0.175670
            D     -0.425197 -1.307304
      id3   C     -1.084448 -0.594710
            D      1.029029 -0.222529
F     id1   C     -0.027381  0.262664
            D     -2.450827  1.436538
      id2   C      1.029116 -0.347283
            D      1.111909  0.219508
      id3   C      1.541434  0.356962
            D      0.912654  0.351822

In [53]:
df4.unstack("ridx1")
df4.unstack("ridx2")

cidx1         A                                                           B  \
cidx2         C                                                           D   
ridx2       id1       id2       id3       id1       id2       id3       id1   
ridx1                                                                         
F     -0.027381  1.029116  1.541434 -2.450827  1.111909  0.912654  0.262664   
M      0.848911 -1.326139 -1.084448  1.801001 -0.425197  1.029029  0.075272   

cidx1                                                    
cidx2                                                    
ridx2       id2       id3       id1       id2       id3  
ridx1                                                    
F     -0.347283  0.356962  1.436538  0.219508  0.351822  
M      0.175670 -0.594710  0.534270 -1.307304 -0.222529