In [1]:
text='정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다.'

In [2]:
import re
token=re.sub('\.', '', text)
token

'정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다'

In [3]:
from konlpy.tag import Okt

In [4]:
okt=Okt()

In [5]:
token=okt.morphs(token)

In [6]:
token

['정부', '가', '발표', '하는', '물가상승률', '과', '소비자', '가', '느끼는', '물가상승률', '은', '다르다']

In [7]:
word2index={}

In [8]:
bow=[]

In [9]:
for v in token:
    if v not in word2index.keys():
        
        word2index[v]=len(word2index)
        bow.insert(len(word2index)-1,1)
    else:
        idx=word2index.get(v)
        bow[idx]=bow[idx]+1
print(word2index)
print(bow)

{'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}
[1, 2, 1, 1, 2, 1, 1, 1, 1, 1]


In [10]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
v=DictVectorizer(sparse=False)
d=[{'a':1, 'b':2}, {'b':3, 'c':1}]
print(v.fit_transform(d))
print(v.feature_names_)

[[1. 2. 0.]
 [0. 3. 1.]]
['a', 'b', 'c']


In [13]:
v.transform({'c':5,'d':2})

array([[0., 0., 5.]])

In [14]:
corpus=['This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
    'The last document?']

In [15]:
v=CountVectorizer()
v.fit(corpus)

CountVectorizer()

In [16]:
v.vocabulary_

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 2,
 'document': 1,
 'second': 6,
 'and': 0,
 'third': 8,
 'one': 5,
 'last': 4}

In [18]:
v.transform(corpus).toarray()

array([[0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0]], dtype=int64)

In [19]:
v.transform(['This is the second document.']).toarray()

array([[0, 1, 0, 1, 0, 0, 1, 1, 0, 1]], dtype=int64)

In [20]:
v=CountVectorizer(stop_words=['and','is','the','this'])
v.fit(corpus)
v.vocabulary_

{'first': 1, 'document': 0, 'second': 4, 'third': 5, 'one': 3, 'last': 2}

In [21]:
v=CountVectorizer(analyzer='char')
v.fit(corpus)
v.vocabulary_

{'t': 16,
 'h': 8,
 'i': 9,
 's': 15,
 ' ': 0,
 'e': 6,
 'f': 7,
 'r': 14,
 'd': 5,
 'o': 13,
 'c': 4,
 'u': 17,
 'm': 11,
 'n': 12,
 '.': 1,
 'a': 3,
 '?': 2,
 'l': 10}

In [22]:
v=CountVectorizer(stop_words='english')
v.fit(corpus)
v.vocabulary_

{'document': 0, 'second': 1}

In [23]:
v=CountVectorizer(token_pattern='t\w+')
v.fit(corpus)
v.vocabulary_

{'this': 2, 'the': 0, 'third': 1}

In [24]:
v=CountVectorizer(ngram_range=(2,2))
v.fit(corpus)
v.vocabulary_

{'this is': 12,
 'is the': 2,
 'the first': 7,
 'first document': 1,
 'the second': 9,
 'second second': 6,
 'second document': 5,
 'and the': 0,
 'the third': 10,
 'third one': 11,
 'is this': 3,
 'this the': 13,
 'the last': 8,
 'last document': 4}

In [26]:
v=CountVectorizer(min_df=2, max_df=4)
v.fit(corpus)
v.vocabulary_, v.stop_words_

({'this': 3, 'is': 2, 'first': 1, 'document': 0},
 {'and', 'last', 'one', 'second', 'the', 'third'})

In [27]:
import pandas as pd
from math import log

C:\Users\msi\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\msi\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [28]:
log(4/(2+1))

0.28768207245178085