In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. 다음과 같은 배열을 만들어라.

In [2]:
a1=np.zeros((3,3))
a2=np.ones((3,2))
a3=np.hstack([a1, a2])
a4=np.array([10,20,30,40,50])
a5=np.stack([a4, a4+50, a4+100])
print(np.tile(np.vstack([a3, a5]), (2,1)))

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


# 2. 다중 인덱스 참조 연습

- 위와 같은 구조의 데이터프레임을 제작하시오.
- B, C1 참조하시오.
- 0번 행,  B,C1  값을 참조하시오.
- 0번행 B, C1 값을 100으로 변경하시오

In [3]:
df=pd.DataFrame(np.random.randn(5, 4), columns=[['A','A','B','B'],['C1','C2','C1','C2']])
df.columns.names=['Cidx1','Cidx2']
df

Cidx1         A                   B          
Cidx2        C1        C2        C1        C2
0     -1.099106 -0.237981 -0.207345  1.029316
1      0.922762 -0.196380  1.138922  1.282086
2      1.609456 -1.248709  1.052943 -0.665258
3     -0.293096  0.336576 -0.161356 -1.464812
4      0.042550  0.972456 -0.653195 -1.197861

In [4]:
print(df['B']['C1'])

0   -0.207345
1    1.138922
2    1.052943
3   -0.161356
4   -0.653195
Name: C1, dtype: float64


In [5]:
print(df.loc[0].loc['B']['C1'])

-0.20734454708754133


In [6]:
df.loc[0].loc['B']['C1']=100
print(df)

Cidx1         A                     B          
Cidx2        C1        C2          C1        C2
0     -1.099106 -0.237981  100.000000  1.029316
1      0.922762 -0.196380    1.138922  1.282086
2      1.609456 -1.248709    1.052943 -0.665258
3     -0.293096  0.336576   -0.161356 -1.464812
4      0.042550  0.972456   -0.653195 -1.197861


# 3. 연관규칙 연습 데이터셋

In [10]:
dataset=np.array([set(['계란','우유']),
    set(['계란','기저귀','맥주','사과']),
    set(['우유','기저귀','맥주','콜라']),
    set(['계란','우유','맥주','기저귀']),
    set(['계란','우유','맥주','콜라'])])
X=set({'계란', '맥주'})
Y=set({'기저귀'})
dataset

array([{'우유', '계란'}, {'사과', '기저귀', '맥주', '계란'}, {'콜라', '기저귀', '우유', '맥주'},
       {'기저귀', '우유', '맥주', '계란'}, {'콜라', '우유', '맥주', '계란'}], dtype=object)

In [11]:
sX_Y=len(dataset[((X|Y)-dataset)==set()])/len(dataset)
print("지지도 =",sX_Y)

지지도 = 0.4


In [12]:
cX_Y=len(dataset[((X|Y)-dataset)==set()])/len(dataset[(X-dataset)==set()])
print("신뢰도 =",cX_Y)

신뢰도 = 0.6666666666666666


In [13]:
sY=len(dataset[(Y-dataset)==set()])/len(dataset)
LiftX_Y=cX_Y/sY
print("향상도 =",LiftX_Y)

향상도 = 1.1111111111111112
