In [1]:
import numpy as np
import pandas as pd

# [빅데이터 분석을 위한 통계 이론]
1. 유클리디안 거리, 코사인 유사도 및 거리에 대해 설명하시오. (코드를 예로 들어서)
2. 표준화와 정규화에 대해 정의하고, 수식에 대해 설명하시오(코드를 예로 들어서)

In [2]:
# 유클리디안 거리는 두 점 사이의 거리로 한 점에 대해 다른 점들이 얼마나 떨어져 있는지를 통해 다른 점이 한 점과 유사한지 확인 할 수 있다

In [3]:
def simDistance(data, name1, name2):
    sum=0
    for i in data[name1]:
        if i in data[name2]:
            sum+=pow(data[name1][i]-data[name2][i], 2)
    return 1/(sqrt(sum)+1)

In [4]:
# 코사인 유사도는 방향을 고려하여 한 점과 다른 점사이의 유사도를 확인할 수 있다.

In [5]:
import math

In [6]:
def simCosine(data, name1, name2):
    sum_name1 = 0
    sum_name2 = 0
    sum = 0
    count = 0
    for i in data[name1]:
        if i in data[name2]: 
            sum_name1 += pow(data[name1][i], 2)
            sum_name2 += pow(data[name2][i], 2)
            sum += data[name1][i]*data[name2][i]
    
    return sum / (math.sqrt(sum_name1)*math.sqrt(sum_name2))

In [7]:
# 표준화(Standardization) : 평균을 기준으로 얼마나 떨어져 있는지를 나타내는 값

In [8]:
data=np.random.randint(20, size=(5,4))
data

array([[18, 10,  7, 16],
       [18,  4,  9,  5],
       [ 0, 10,  3,  8],
       [14, 14, 15,  5],
       [11,  6,  9,  0]])

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
StandardScaler().fit_transform(data)

array([[ 0.87279743,  0.3441236 , -0.4125685 ,  1.74613612],
       [ 0.87279743, -1.3764944 ,  0.10314212, -0.34163533],
       [-1.83588426,  0.3441236 , -1.44398974,  0.22775689],
       [ 0.27086817,  1.49120227,  1.65027399, -0.34163533],
       [-0.18057878, -0.80295507,  0.10314212, -1.29062235]])

In [11]:
(data-np.mean(data, axis=0))/np.std(data, axis=0)

array([[ 0.87279743,  0.3441236 , -0.4125685 ,  1.74613612],
       [ 0.87279743, -1.3764944 ,  0.10314212, -0.34163533],
       [-1.83588426,  0.3441236 , -1.44398974,  0.22775689],
       [ 0.27086817,  1.49120227,  1.65027399, -0.34163533],
       [-0.18057878, -0.80295507,  0.10314212, -1.29062235]])

In [12]:
# 정규화(Normalization) : 데이터의 범위를 0과 1로 변환하여 데이터 분포를 조정하는 방법

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
MinMaxScaler().fit_transform(data)

array([[1.        , 0.6       , 0.33333333, 1.        ],
       [1.        , 0.        , 0.5       , 0.3125    ],
       [0.        , 0.6       , 0.        , 0.5       ],
       [0.77777778, 1.        , 1.        , 0.3125    ],
       [0.61111111, 0.2       , 0.5       , 0.        ]])

In [15]:
(data-data.min(axis=0))/(data.max(axis=0)-data.min(axis=0))

array([[1.        , 0.6       , 0.33333333, 1.        ],
       [1.        , 0.        , 0.5       , 0.3125    ],
       [0.        , 0.6       , 0.        , 0.5       ],
       [0.77777778, 1.        , 1.        , 0.3125    ],
       [0.61111111, 0.2       , 0.5       , 0.        ]])

# [파이썬 분석 및 시각화 라이브러리]
1. 타이타닉 데이터에 대해 아래와 같은 작업을 수행하시오.

1) Pclass를 원핫인코딩

2) Age를 이산화(5개 구간으로 나눔)

3) embarked를 원핫인코딩

2. bins = [5, 20, 30, 40, 60, 90]

labels = ["미성년자", "청년", "중년", "장년", "노년"]

타이타닉호 승객을 사망자와 생존자 그룹으로 나누고 각 그룹에 대해 '미성년자', '청년', '중년', '장년', '노년' 승객의 비율을 구한다. 각 그룹 별로 비율의 전체 합은 1이 되어야 한다.

In [16]:
train=pd.read_csv("train.csv")
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [17]:
test=pd.read_csv("test.csv")
test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [18]:
train_test=[train, test]

In [19]:
train.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [20]:
train["Pclass1"]=np.where(train["Pclass"]==1, 1, 0)
train["Pclass1"].value_counts()

0    675
1    216
Name: Pclass1, dtype: int64

In [21]:
train["Pclass2"]=np.where(train["Pclass"]==2, 1, 0)
train["Pclass2"].value_counts()

0    707
1    184
Name: Pclass2, dtype: int64

In [22]:
train["Pclass3"]=np.where(train["Pclass"]==3, 1, 0)
train["Pclass3"].value_counts()

1    491
0    400
Name: Pclass3, dtype: int64

In [23]:
train["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [24]:
train['Age'].isnull().sum()

177

In [25]:
train['Age'].mean()

29.69911764705882

In [26]:
train['Age']=np.where(train['Age'].isnull(), int(train['Age'].mean()), train['Age'])
train['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    29.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [27]:
train['AgeBand']=pd.cut(train['Age'], 5)

In [28]:
train['AgeBand'].value_counts()

(16.336, 32.252]    523
(32.252, 48.168]    188
(0.34, 16.336]      100
(48.168, 64.084]     69
(64.084, 80.0]       11
Name: AgeBand, dtype: int64

In [29]:
for dataset in train_test:
    dataset.loc[dataset['Age']<=16, 'Age']=0
    dataset.loc[(dataset['Age']>16) & (dataset['Age']<=32), 'Age']=1
    dataset.loc[(dataset['Age']>32) & (dataset['Age']<=48), 'Age']=2
    dataset.loc[(dataset['Age']>48) & (dataset['Age']<=64), 'Age']=3
    dataset.loc[(dataset['Age']>64) , 'Age']=4

In [30]:
train.Age.value_counts()

1.0    523
2.0    188
0.0    100
3.0     69
4.0     11
Name: Age, dtype: int64

In [31]:
train.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [32]:
train["Embarked_S"]=np.where(train["Embarked"]=="S", 1, 0)
train["Embarked_S"].value_counts()

1    644
0    247
Name: Embarked_S, dtype: int64

In [33]:
train["Embarked_C"]=np.where(train["Embarked"]=="C", 1, 0)
train["Embarked_C"].value_counts()

0    723
1    168
Name: Embarked_C, dtype: int64

In [34]:
train["Embarked_Q"]=np.where(train["Embarked"]=="Q", 1, 0)
train["Embarked_Q"].value_counts()

0    814
1     77
Name: Embarked_Q, dtype: int64

In [35]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  1.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  2.0      1   
2                               Heikkinen, Miss. Laina  female  1.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  2.0      1   
4                             Allen, Mr. William Henry    male  2.0      0   
..                                                 ...     ...  ...    ...   
886                              Montvila, Rev. Juozas    male  1.0      0   
887                       Graham, Miss. Margaret Edith  female  1.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  1.0      1   
889                              Behr, Mr. Karl Howell    male  1.0      0   
890                                Dooley, Mr. Patrick    male  1.0      0   

     Parch            Ticket     Fare Cabin Embarked  Pclass1  Pclass2  \
0        0         A/5 21171   7.2500   NaN        S        0        0   
1        0          PC 17599  71.2833   C85        C        1        0   
2        0  STON/O2. 3101282   7.9250   NaN        S        0        0   
3        0            113803  53.1000  C123        S        1        0   
4        0            373450   8.0500   NaN        S        0        0   
..     ...               ...      ...   ...      ...      ...      ...   
886      0            211536  13.0000   NaN        S        0        1   
887      0            112053  30.0000   B42        S        1        0   
888      2        W./C. 6607  23.4500   NaN        S        0        0   
889      0            111369  30.0000  C148        C        1        0   
890      0            370376   7.7500   NaN        Q        0        0   

     Pclass3           AgeBand  Embarked_S  Embarked_C  Embarked_Q  
0          1  (16.336, 32.252]           1           0           0  
1          0  (32.252, 48.168]           0           1           0  
2          1  (16.336, 32.252]           1           0           0  
3          0  (32.252, 48.168]           1           0           0  
4          1  (32.252, 48.168]           1           0           0  
..       ...               ...         ...         ...         ...  
886        0  (16.336, 32.252]           1           0           0  
887        0  (16.336, 32.252]           1           0           0  
888        1  (16.336, 32.252]           1           0           0  
889        0  (16.336, 32.252]           0           1           0  
890        1  (16.336, 32.252]           0           0           1  

[891 rows x 19 columns]

# 
bins = [5, 20, 30, 40, 60, 90]

labels = ["미성년자", "청년", "중년", "장년", "노년"]

타이타닉호 승객을 사망자와 생존자 그룹으로 나누고 각 그룹에 대해 '미성년자', '청년', '중년', '장년', '노년' 승객의 비율을 구한다. 각 그룹 별로 비율의 전체 합은 1이 되어야 한다.

In [36]:
train=pd.read_csv("train.csv")

In [37]:
train['Age']=np.where(train['Age'].isnull(), int(train['Age'].mean()), train['Age'])
train['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    29.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [38]:
train['AgeName']=pd.cut(train['Age'], bins = [5, 20, 30, 40, 60, 90], labels = ["미성년자", "청년", "중년", "장년", "노년"])

In [39]:
train['AgeName']

0        청년
1        중년
2        청년
3        중년
4        중년
       ... 
886      청년
887    미성년자
888      청년
889      청년
890      중년
Name: AgeName, Length: 891, dtype: category
Categories (5, object): [미성년자 < 청년 < 중년 < 장년 < 노년]

In [40]:
train.groupby(['Survived', 'AgeName'])['Age'].count()

Survived  AgeName
0         미성년자        84
          청년         271
          중년          86
          장년          78
          노년          17
1         미성년자        51
          청년         136
          중년          69
          장년          50
          노년           5
Name: Age, dtype: int64

In [41]:
Not_Survived_cnt=train.groupby(['Survived'])['Age'].count()[0]
Survived_cnt=train.groupby(['Survived'])['Age'].count()[1]
train.groupby(['Survived'])['Age'].count()

Survived
0    549
1    342
Name: Age, dtype: int64

In [42]:
train.groupby(['Survived', 'AgeName'])['Age'].count()[0]/Not_Survived_cnt

AgeName
미성년자    0.153005
청년      0.493625
중년      0.156648
장년      0.142077
노년      0.030965
Name: Age, dtype: float64

In [43]:
train.groupby(['Survived', 'AgeName'])['Age'].count()[1]/Survived_cnt

AgeName
미성년자    0.149123
청년      0.397661
중년      0.201754
장년      0.146199
노년      0.014620
Name: Age, dtype: float64